export const EVIDENCE_CLASSES = ['A', 'B', 'C', 'D', 'E', 'F'] as const

export type EvidenceClass = typeof EVIDENCE_CLASSES[number]

export const EVIDENCE_TYPES = [
  'camera/photo',
  'video',
  'field note',
  'document',
  'permit/status proof',
  'test result',
  'manufacturer/spec document',
  'professional assurance document',
] as const

export type EvidenceType = typeof EVIDENCE_TYPES[number]

export const LAUNCH_PRIORITIES = ['P0', 'P1', 'P2'] as const

export type LaunchPriority = typeof LAUNCH_PRIORITIES[number]

export type EvidencePolicyStatus =
  | 'ready_for_sprint_02b_ui_copy'
  | 'requires_template_model_change'
  | 'requires_professional_ahj_review'
  | 'documented_exception'

export interface InspectionEvidencePolicyEntry {
  stageId: `S${string}`
  itemCode: string
  itemLabel: string
  proMatrixClasses: EvidenceClass[]
  reconciledClass: EvidenceClass
  evidenceTypes: EvidenceType[]
  sourceMatrixRows: string[]
  reason: string
  launchPriority: LaunchPriority
  implementationStatus: EvidencePolicyStatus
  mismatch?: string
  professionalAhjReviewQuestion?: string
}

export interface SystemStateEvidenceControl {
  id: string
  label: string
  evidenceClass: EvidenceClass
  reason: string
  uploadDriven: false
}

export const UNIVERSAL_OUTCOME_NOTE_RULE = {
  correctionsRequired: 'field note',
  holdCannotProceed: 'field note',
  notApplicable: 'field note',
  source:
    'Pro evidence matrix universal rule: any Corrections Required, Hold / Cannot Proceed, or N/A selection requires at least a field note unless the current product model has a safer or more specific rule.',
} as const

export const SYSTEM_STATE_EVIDENCE_CONTROLS: SystemStateEvidenceControl[] = [
  {
    id: 'S15.1',
    label: 'Prerequisite specialty stages digitally sealed',
    evidenceClass: 'F',
    reason:
      'Pro matrix says this must remain system-state logic validated by workflow/seal state, not an upload-driven checklist evidence row.',
    uploadDriven: false,
  },
]

export const INSPECTION_EVIDENCE_POLICY: InspectionEvidencePolicyEntry[] = [
  {
    stageId: 'S01',
    itemCode: 'S01-01',
    itemLabel: 'Project Address and Legal Description',
    proMatrixClasses: ['E'],
    reconciledClass: 'E',
    evidenceTypes: ['document', 'permit/status proof', 'field note'],
    sourceMatrixRows: ['S01 survey pins and property setbacks verified', 'Decision rules: permit/status proof and dispute record'],
    reason: 'Current row is a project-identity document check, not a field-observation row; evidence is useful for disputes but should remain verify-existing until template review.',
    launchPriority: 'P1',
    implementationStatus: 'ready_for_sprint_02b_ui_copy',
    mismatch: 'No exact Pro row exists for civic address/legal-description package readiness.',
    professionalAhjReviewQuestion: 'Should address/legal-description proof be satisfied by permit cover page metadata instead of uploads?',
  },
  {
    stageId: 'S01',
    itemCode: 'S01-02',
    itemLabel: 'Governing Authority, Code Path, and Jurisdiction Overlay',
    proMatrixClasses: ['E'],
    reconciledClass: 'E',
    evidenceTypes: ['permit/status proof', 'document', 'field note'],
    sourceMatrixRows: ['Decision rules: permit/status gates', 'Professional-review queue: authority-boundary group'],
    reason: 'Code path and AHJ identification affect scope but are primarily record metadata; collect supporting proof without hard upload enforcement.',
    launchPriority: 'P1',
    implementationStatus: 'requires_template_model_change',
    mismatch: 'Current active row is broader than any single Pro matrix checklist item.',
    professionalAhjReviewQuestion: 'Can jurisdiction/code path be derived from permit metadata instead of field evidence?',
  },
  {
    stageId: 'S01',
    itemCode: 'S01-03',
    itemLabel: 'Project Type, Building Type, and Structural Scope Classification',
    proMatrixClasses: ['D'],
    reconciledClass: 'D',
    evidenceTypes: ['field note', 'document'],
    sourceMatrixRows: ['Decision rules: N/A scope decisions require justification', 'Professional-review queue: scope/applicability group'],
    reason: 'This is a scope/applicability row; the Pro matrix supports evidence when a scope path is treated as not applicable or exceptional.',
    launchPriority: 'P1',
    implementationStatus: 'requires_template_model_change',
    mismatch: 'Current row is a normalized scope classifier, not one packet row.',
    professionalAhjReviewQuestion: 'Which project-type signals should hide downstream rows instead of requiring repeated N/A evidence?',
  },
  {
    stageId: 'S01',
    itemCode: 'S01-04',
    itemLabel: 'Site Record, Drawings, and Revision Package Readiness',
    proMatrixClasses: ['C', 'D'],
    reconciledClass: 'C',
    evidenceTypes: ['document', 'permit/status proof', 'field note'],
    sourceMatrixRows: ['S15 final inspection passed or ready for authority review', 'Decision rules: missing prerequisite permits or documents should hold'],
    reason: 'Missing drawings or revision records are prerequisite-readiness blockers rather than routine photo evidence.',
    launchPriority: 'P0',
    implementationStatus: 'requires_template_model_change',
    mismatch: 'Current active row aggregates several Pro document-readiness concerns.',
    professionalAhjReviewQuestion: 'Should drawing revision completeness be a system checklist state instead of an inspector upload prompt?',
  },
  {
    stageId: 'S01',
    itemCode: 'S01-05',
    itemLabel: 'Registered Professional and Permit Coordination Flags',
    proMatrixClasses: ['A', 'D'],
    reconciledClass: 'D',
    evidenceTypes: ['professional assurance document', 'document', 'field note'],
    sourceMatrixRows: ['S15 Schedules C-A and C-B or equivalent letters of assurance', 'Professional-review queue: professional reliance group'],
    reason: 'Professional reliance is conditional by permit scope; if marked not applicable or exceptional, a scope note or document should support the decision.',
    launchPriority: 'P0',
    implementationStatus: 'requires_professional_ahj_review',
    professionalAhjReviewQuestion: 'Which RP flags require uploaded assurance documents versus metadata-only confirmation?',
  },
  {
    stageId: 'S02',
    itemCode: 'S02-01',
    itemLabel: 'Zoning and Civic Approvals',
    proMatrixClasses: ['C'],
    reconciledClass: 'C',
    evidenceTypes: ['permit/status proof', 'document', 'field note'],
    sourceMatrixRows: ['Decision rules: permit/status proof gates', 'Professional-review queue: authority-boundary group'],
    reason: 'Missing zoning or civic approval should block progress as an administrative prerequisite.',
    launchPriority: 'P0',
    implementationStatus: 'requires_template_model_change',
    professionalAhjReviewQuestion: 'Can approval status be read from AHJ metadata instead of uploaded proof?',
  },
  {
    stageId: 'S02',
    itemCode: 'S02-02',
    itemLabel: 'Site Servicing and Access',
    proMatrixClasses: ['C', 'A'],
    reconciledClass: 'C',
    evidenceTypes: ['permit/status proof', 'document', 'field note'],
    sourceMatrixRows: ['S14 stormwater management compliant with municipal requirements', 'S15 required agency reviews complete'],
    reason: 'Servicing/access gaps are approval or cannot-proceed conditions; routine pass should not create generic uploads before model support exists.',
    launchPriority: 'P0',
    implementationStatus: 'requires_template_model_change',
    professionalAhjReviewQuestion: 'Which servicing approvals should be modeled as status fields?',
  },
  {
    stageId: 'S02',
    itemCode: 'S02-03',
    itemLabel: 'Site Clearing and Environment',
    proMatrixClasses: ['E'],
    reconciledClass: 'E',
    evidenceTypes: ['camera/photo', 'field note'],
    sourceMatrixRows: ['S01 temporary erosion and sediment control in place', 'S14 erosion and sediment controls removed or stabilized'],
    reason: 'Environmental controls are visible and revisitable in many cases; evidence is useful but should not hard-gate launch pass.',
    launchPriority: 'P1',
    implementationStatus: 'ready_for_sprint_02b_ui_copy',
    professionalAhjReviewQuestion: 'Should municipal site-servicing conditions elevate this row to required evidence on selected projects?',
  },
  {
    stageId: 'S03',
    itemCode: 'S03-01',
    itemLabel: 'Site and Architectural Matrix',
    proMatrixClasses: ['E', 'D'],
    reconciledClass: 'E',
    evidenceTypes: ['document', 'field note'],
    sourceMatrixRows: ['Decision rules: scope/applicability rows need N/A justification', 'Professional-review queue: authority-boundary group'],
    reason: 'The active row is package-readiness documentation; the Pro matrix supports targeted document proof but not mandatory uploads merely because the row exists.',
    launchPriority: 'P1',
    implementationStatus: 'requires_template_model_change',
    mismatch: 'No exact Pro row exists for the current package-matrix container.',
    professionalAhjReviewQuestion: 'Which architectural matrix fields should become conditional visibility controls?',
  },
  {
    stageId: 'S03',
    itemCode: 'S03-02',
    itemLabel: 'Safety and Structural Calculations',
    proMatrixClasses: ['D', 'A'],
    reconciledClass: 'D',
    evidenceTypes: ['document', 'professional assurance document', 'field note'],
    sourceMatrixRows: ['S02 structural shop drawings', 'S04 structural shop drawings reviewed', 'Professional-review queue: professional reliance group'],
    reason: 'Calculation evidence is professional-document governance and should be conditional to project scope before hard enforcement.',
    launchPriority: 'P1',
    implementationStatus: 'requires_professional_ahj_review',
    professionalAhjReviewQuestion: 'Should Vero collect calculation documents or only record RP/permit-review status?',
  },
  {
    stageId: 'S03',
    itemCode: 'S03-03',
    itemLabel: 'Drawing Packages and Assurances',
    proMatrixClasses: ['A', 'D'],
    reconciledClass: 'D',
    evidenceTypes: ['document', 'professional assurance document', 'field note'],
    sourceMatrixRows: ['S15 Schedules C-A and C-B or equivalent letters of assurance', 'Professional-review queue: professional reliance group'],
    reason: 'Assurances are mandatory where applicable, but applicability must be governed before upload enforcement.',
    launchPriority: 'P0',
    implementationStatus: 'requires_professional_ahj_review',
    professionalAhjReviewQuestion: 'Which Schedules/letters are required at permit package versus final closeout?',
  },
  {
    stageId: 'S04',
    itemCode: 'S04-01',
    itemLabel: 'Pre-Disturbance Controls and Demolition',
    proMatrixClasses: ['A', 'C', 'E'],
    reconciledClass: 'A',
    evidenceTypes: ['camera/photo', 'field note', 'permit/status proof'],
    sourceMatrixRows: ['S01 underground utilities located and protected', 'S01 excavation shoring and worker safety measures', 'S01 temporary erosion and sediment control in place'],
    reason: 'Pre-disturbance conditions include safety/status gates and conditions that are lost once excavation or demolition proceeds.',
    launchPriority: 'P0',
    implementationStatus: 'ready_for_sprint_02b_ui_copy',
    professionalAhjReviewQuestion: 'Should BC One Call or demolition permit references be structured fields?',
  },
  {
    stageId: 'S04',
    itemCode: 'S04-02',
    itemLabel: 'Survey, Setbacks, Siting, and Flood Level Verification',
    proMatrixClasses: ['E', 'A'],
    reconciledClass: 'E',
    evidenceTypes: ['camera/photo', 'field note', 'document'],
    sourceMatrixRows: ['S01 survey pins and property setbacks verified', 'S03 foundation dimensions match structural drawings'],
    reason: 'Survey/siting evidence is dispute-useful; current active row is broader than the Pro A row and needs conditional project triggers.',
    launchPriority: 'P1',
    implementationStatus: 'requires_template_model_change',
    professionalAhjReviewQuestion: 'Should flood level or siting certificate requirements elevate this row to A on selected permits?',
  },
  {
    stageId: 'S04',
    itemCode: 'S04-03',
    itemLabel: 'Earthworks, Geotechnical, and Soil Conditions',
    proMatrixClasses: ['A'],
    reconciledClass: 'A',
    evidenceTypes: ['camera/photo', 'field note', 'document', 'test result'],
    sourceMatrixRows: ['S01 soil conditions consistent with geotechnical report', 'S02 geotechnical bearing capacity of soil', 'S02 compaction of engineered fill'],
    reason: 'Earthworks and soil conditions are concealed or difficult to verify later and may require geotechnical/test documentation.',
    launchPriority: 'P0',
    implementationStatus: 'ready_for_sprint_02b_ui_copy',
    professionalAhjReviewQuestion: 'When should geotechnical memo or compaction report be mandatory versus optional?',
  },
  {
    stageId: 'S04',
    itemCode: 'S04-04',
    itemLabel: 'Site Safety, Environmental Controls, and Temporary Drainage',
    proMatrixClasses: ['C', 'E'],
    reconciledClass: 'C',
    evidenceTypes: ['field note', 'camera/photo'],
    sourceMatrixRows: ['S01 excavation shoring and worker safety measures', 'S01 temporary erosion and sediment control in place'],
    reason: 'Unsafe or inaccessible site conditions should stop the inspection; visible environmental controls remain recommended evidence.',
    launchPriority: 'P0',
    implementationStatus: 'ready_for_sprint_02b_ui_copy',
    professionalAhjReviewQuestion: 'Should this row be reframed as safe inspection access rather than WorkSafeBC compliance?',
  },
  {
    stageId: 'S05',
    itemCode: 'S05-01',
    itemLabel: 'Footings, Foundation Walls, Rebar, and Embedded Items',
    proMatrixClasses: ['A'],
    reconciledClass: 'A',
    evidenceTypes: ['camera/photo', 'field note'],
    sourceMatrixRows: ['S02 structural capacity, anchorage, and seismic restraint', 'S03 anchor bolts, hold-downs, and embedded hardware correct'],
    reason: 'Rebar, anchors, hold-downs, and embedded items are concealed by concrete and have high structural consequence.',
    launchPriority: 'P0',
    implementationStatus: 'ready_for_sprint_02b_ui_copy',
    professionalAhjReviewQuestion: 'Should close-up evidence be required at every hold-down or representative locations?',
  },
  {
    stageId: 'S05',
    itemCode: 'S05-02',
    itemLabel: 'Drainage, Dampproofing, and Foundation Protection',
    proMatrixClasses: ['A'],
    reconciledClass: 'A',
    evidenceTypes: ['camera/photo', 'field note', 'manufacturer/spec document'],
    sourceMatrixRows: ['S02 dampproofing and waterproofing below grade', 'S02 site and foundation drainage', 'S03 damp-proofing or waterproofing applied'],
    reason: 'Foundation protection and drainage are hidden after backfill and are common dispute sources.',
    launchPriority: 'P0',
    implementationStatus: 'ready_for_sprint_02b_ui_copy',
    professionalAhjReviewQuestion: 'Should drain tile and discharge path photos become separate sub-evidence prompts?',
  },
  {
    stageId: 'S05',
    itemCode: 'S05-03',
    itemLabel: 'Slab Preparation, Radon, Soil Gas, and Under-Slab Conditions',
    proMatrixClasses: ['A'],
    reconciledClass: 'A',
    evidenceTypes: ['camera/photo', 'field note', 'manufacturer/spec document'],
    sourceMatrixRows: ['Launch-critical: concealed structural and enclosure work', 'S03 drainage sleeves and utility penetrations in place'],
    reason: 'Under-slab layers, penetrations, and soil-gas measures are concealed after the slab pour.',
    launchPriority: 'P0',
    implementationStatus: 'ready_for_sprint_02b_ui_copy',
    professionalAhjReviewQuestion: 'Should radon/soil-gas systems have dedicated evidence prompts by jurisdiction?',
  },
  {
    stageId: 'S05',
    itemCode: 'S05-04',
    itemLabel: 'Concrete Pour, Placement, Curing, and Post-Pour Review',
    proMatrixClasses: ['A', 'B'],
    reconciledClass: 'A',
    evidenceTypes: ['camera/photo', 'field note', 'test result', 'document'],
    sourceMatrixRows: ['S03 concrete mix design and compressive strength confirmed', 'S03 curing and cold-weather protection measures'],
    reason: 'Concrete placement and test records are formal evidence points; weather/curing evidence matters when conditions are deficient.',
    launchPriority: 'P0',
    implementationStatus: 'ready_for_sprint_02b_ui_copy',
    professionalAhjReviewQuestion: 'Should cylinder report be required before pass or before final seal?',
  },
  {
    stageId: 'S06',
    itemCode: 'S06-01',
    itemLabel: 'Vertical and Horizontal Framing',
    proMatrixClasses: ['A'],
    reconciledClass: 'A',
    evidenceTypes: ['camera/photo', 'field note'],
    sourceMatrixRows: ['S04 structural framing matches approved drawings', 'S04 roof structure and bracing complete'],
    reason: 'Framing members and load paths are concealed or difficult to verify after insulation/drywall.',
    launchPriority: 'P0',
    implementationStatus: 'ready_for_sprint_02b_ui_copy',
    professionalAhjReviewQuestion: 'Which spans/header locations need annotated photos rather than general walkthroughs?',
  },
  {
    stageId: 'S06',
    itemCode: 'S06-02',
    itemLabel: 'Lateral and Seismic Systems',
    proMatrixClasses: ['A'],
    reconciledClass: 'A',
    evidenceTypes: ['camera/photo', 'field note'],
    sourceMatrixRows: ['S04 shear wall nailing, hold-downs, and straps'],
    reason: 'Lateral and seismic details are concealed and high consequence.',
    launchPriority: 'P0',
    implementationStatus: 'ready_for_sprint_02b_ui_copy',
    professionalAhjReviewQuestion: 'Should fastener spacing and hold-down photos be mandatory at each braced wall line?',
  },
  {
    stageId: 'S06',
    itemCode: 'S06-03',
    itemLabel: 'Stairs, Openings, Fire Separations, and Engineering',
    proMatrixClasses: ['A', 'D'],
    reconciledClass: 'A',
    evidenceTypes: ['camera/photo', 'field note', 'document', 'professional assurance document'],
    sourceMatrixRows: ['S04 fire blocking and draft stopping installed', 'S04 structural shop drawings reviewed'],
    reason: 'Openings, separations, and engineering coordination include concealed fire/structural details; document governance remains review-sensitive.',
    launchPriority: 'P0',
    implementationStatus: 'requires_professional_ahj_review',
    professionalAhjReviewQuestion: 'Which engineered stair/opening documents belong in RP review rather than inspector evidence?',
  },
  {
    stageId: 'S07',
    itemCode: 'S07-01',
    itemLabel: 'Sheathing, WRB, and Weather Barrier',
    proMatrixClasses: ['A'],
    reconciledClass: 'A',
    evidenceTypes: ['camera/photo', 'manufacturer/spec document'],
    sourceMatrixRows: ['S04 weather-resistant barrier installed', 'S05 roof sheathing grade and nailing pattern'],
    reason: 'Weather barrier and sheathing conditions are concealed by cladding/roofing.',
    launchPriority: 'P0',
    implementationStatus: 'ready_for_sprint_02b_ui_copy',
    professionalAhjReviewQuestion: 'Should transition details be required close-ups?',
  },
  {
    stageId: 'S07',
    itemCode: 'S07-02',
    itemLabel: 'Penetrations, Openings, Flashings, and Cladding Integration',
    proMatrixClasses: ['A'],
    reconciledClass: 'A',
    evidenceTypes: ['camera/photo', 'manufacturer/spec document'],
    sourceMatrixRows: ['S04 windows and exterior doors installed and flashed', 'S10 weather-resistant barrier continuity at penetrations'],
    reason: 'Openings, penetrations, and flashings are high leak-risk details concealed by cladding or finishes.',
    launchPriority: 'P0',
    implementationStatus: 'ready_for_sprint_02b_ui_copy',
    professionalAhjReviewQuestion: 'When should manufacturer installation details be mandatory?',
  },
  {
    stageId: 'S07',
    itemCode: 'S07-03',
    itemLabel: 'Roof System, Drainage, Ventilation, and Weatherproofing',
    proMatrixClasses: ['A'],
    reconciledClass: 'A',
    evidenceTypes: ['camera/photo', 'field note'],
    sourceMatrixRows: ['S05 ice and water shield at eaves and valleys', 'S05 roofing underlayment installed', 'S05 attic ventilation provisions installed'],
    reason: 'Roof underlayment, eave protection, penetrations, and ventilation paths are concealed or hard to prove later.',
    launchPriority: 'P0',
    implementationStatus: 'ready_for_sprint_02b_ui_copy',
    professionalAhjReviewQuestion: 'Should intake and exhaust ventilation evidence be separate prompts?',
  },
  {
    stageId: 'S07',
    itemCode: 'S07-04',
    itemLabel: 'Envelope Field Review and Assurance',
    proMatrixClasses: ['E', 'D', 'A'],
    reconciledClass: 'D',
    evidenceTypes: ['document', 'professional assurance document', 'field note'],
    sourceMatrixRows: ['S10 building enclosure design and performance confirmed', 'S10 building enclosure shop drawings reviewed', 'Professional-review queue: professional reliance group'],
    reason: 'Envelope assurance is professional/document governance; applicability must be resolved before upload enforcement.',
    launchPriority: 'P1',
    implementationStatus: 'requires_professional_ahj_review',
    professionalAhjReviewQuestion: 'Should envelope field review evidence be RP documentation rather than inspector photos?',
  },
  {
    stageId: 'S08',
    itemCode: 'S08-01',
    itemLabel: 'Fire Separations and Blocking',
    proMatrixClasses: ['A'],
    reconciledClass: 'A',
    evidenceTypes: ['camera/photo', 'manufacturer/spec document'],
    sourceMatrixRows: ['S04 fire blocking and draft stopping installed', 'S12 fire-rated assemblies correctly constructed', 'S12 fire-rated penetration firestopping'],
    reason: 'Fire separations and blocking are concealed life-safety conditions.',
    launchPriority: 'P0',
    implementationStatus: 'ready_for_sprint_02b_ui_copy',
    professionalAhjReviewQuestion: 'Should listed assembly numbers be captured in structured notes?',
  },
  {
    stageId: 'S08',
    itemCode: 'S08-02',
    itemLabel: 'Egress, Smoke/CO Alarms, Emergency Lighting, and Exit Sign Rough-In',
    proMatrixClasses: ['A', 'E'],
    reconciledClass: 'A',
    evidenceTypes: ['camera/photo', 'video', 'field note'],
    sourceMatrixRows: ['S13 emergency lighting and exit signs functional', 'S13 smoke and CO detector placement', 'S13 means of egress complete and unobstructed'],
    reason: 'Life-safety devices and egress readiness can be occupancy-critical; functional elements justify required evidence where applicable.',
    launchPriority: 'P0',
    implementationStatus: 'ready_for_sprint_02b_ui_copy',
    professionalAhjReviewQuestion: 'Should functional tests be video-preferred only for emergency lighting and exit signage?',
  },
  {
    stageId: 'S08',
    itemCode: 'S08-03',
    itemLabel: 'Accessibility and Guards',
    proMatrixClasses: ['E'],
    reconciledClass: 'E',
    evidenceTypes: ['camera/photo', 'field note'],
    sourceMatrixRows: ['S13 means of egress complete and unobstructed', 'Decision rules: likely dispute record'],
    reason: 'Guards and accessibility clearances are visible and can often be revisited, but evidence improves dispute defensibility.',
    launchPriority: 'P1',
    implementationStatus: 'requires_professional_ahj_review',
    professionalAhjReviewQuestion: 'Which occupancy classes or adaptable-housing paths should elevate this to A?',
  },
  {
    stageId: 'S08',
    itemCode: 'S08-04',
    itemLabel: 'Fire Suppression System Rough-In',
    proMatrixClasses: ['A'],
    reconciledClass: 'A',
    evidenceTypes: ['camera/photo', 'document', 'test result', 'field note'],
    sourceMatrixRows: ['S07 sprinkler system matches approved hydraulic calculations', 'S07 concealed areas inspected before enclosure', 'S07 system pressure test completed and documented'],
    reason: 'Suppression rough-in combines concealed work, approved calculations, and pressure-test evidence.',
    launchPriority: 'P0',
    implementationStatus: 'ready_for_sprint_02b_ui_copy',
    professionalAhjReviewQuestion: 'Which contractor certificates or AHJ records are acceptable test evidence?',
  },
  {
    stageId: 'S08',
    itemCode: 'S08-05',
    itemLabel: 'Fire Alarm Rough-In',
    proMatrixClasses: ['A'],
    reconciledClass: 'A',
    evidenceTypes: ['camera/photo', 'document', 'field note'],
    sourceMatrixRows: ['S08 fire protection of wiring for emergency systems', 'S13 fire alarm system functional test completed'],
    reason: 'Fire alarm rough-in and emergency wiring protection are life-safety and may be concealed.',
    launchPriority: 'P0',
    implementationStatus: 'ready_for_sprint_02b_ui_copy',
    professionalAhjReviewQuestion: 'Should functional acceptance reports live at rough-in, final, or both?',
  },
  {
    stageId: 'S09',
    itemCode: 'S09-01',
    itemLabel: 'Permit Scope, Readiness, and Visibility',
    proMatrixClasses: ['C'],
    reconciledClass: 'C',
    evidenceTypes: ['permit/status proof', 'field note'],
    sourceMatrixRows: ['S09 plumbing systems match approved permit scope'],
    reason: 'Permit mismatch or readiness failure should hold the inspection rather than create routine upload burden.',
    launchPriority: 'P0',
    implementationStatus: 'requires_template_model_change',
    professionalAhjReviewQuestion: 'Can permit metadata satisfy this automatically?',
  },
  {
    stageId: 'S09',
    itemCode: 'S09-02',
    itemLabel: 'Potable Water Supply Rough-In',
    proMatrixClasses: ['A'],
    reconciledClass: 'A',
    evidenceTypes: ['camera/photo', 'test result', 'field note'],
    sourceMatrixRows: ['S09 structural capacity and seismic restraint of plumbing components', 'S07 water supply connection and backflow preventer'],
    reason: 'Water rough-in can be concealed and may require pressure/backflow evidence depending on scope.',
    launchPriority: 'P0',
    implementationStatus: 'ready_for_sprint_02b_ui_copy',
    professionalAhjReviewQuestion: 'Should pressure-test evidence be required here or at closeout?',
  },
  {
    stageId: 'S09',
    itemCode: 'S09-03',
    itemLabel: 'Drain, Waste, Vent, and Drainage Rough-In',
    proMatrixClasses: ['A'],
    reconciledClass: 'A',
    evidenceTypes: ['camera/photo', 'test result', 'field note'],
    sourceMatrixRows: ['S09 roof drainage systems', 'S09 site and foundation drainage systems', 'Launch-critical: concealed drainage work'],
    reason: 'DWV and drainage routes are concealed and common dispute/failure sources.',
    launchPriority: 'P0',
    implementationStatus: 'ready_for_sprint_02b_ui_copy',
    professionalAhjReviewQuestion: 'Should DWV test result and slope/cleanout photos be distinct prompts?',
  },
  {
    stageId: 'S09',
    itemCode: 'S09-04',
    itemLabel: 'Testing, Fixtures, and Fire Separation Penetrations',
    proMatrixClasses: ['A', 'D'],
    reconciledClass: 'A',
    evidenceTypes: ['camera/photo', 'test result', 'manufacturer/spec document', 'field note'],
    sourceMatrixRows: ['S09 fire separation continuity at plumbing penetrations', 'S09 functional testing of plumbing fire emergency systems'],
    reason: 'Testing and rated penetrations are formal/concealed life-safety evidence points.',
    launchPriority: 'P0',
    implementationStatus: 'ready_for_sprint_02b_ui_copy',
    professionalAhjReviewQuestion: 'Which plumbing fire-emergency tests are in scope for this row?',
  },
  {
    stageId: 'S09',
    itemCode: 'S09-05',
    itemLabel: 'City Connection, Backflow, Sump, and Jurisdictional Requirements',
    proMatrixClasses: ['A'],
    reconciledClass: 'A',
    evidenceTypes: ['camera/photo', 'permit/status proof', 'test result', 'field note'],
    sourceMatrixRows: ['S09 sewer/storm connection placard data VBBL only', 'S07 water supply connection and backflow preventer'],
    reason: 'Connection, backflow, sump, and jurisdictional records are high-dispute servicing/status evidence points.',
    launchPriority: 'P0',
    implementationStatus: 'requires_template_model_change',
    professionalAhjReviewQuestion: 'Should Vancouver placard data be a structured field instead of freeform upload?',
  },
  {
    stageId: 'S10',
    itemCode: 'S10-01',
    itemLabel: 'Electrical Permit and Service Readiness',
    proMatrixClasses: ['C', 'E', 'A'],
    reconciledClass: 'A',
    evidenceTypes: ['camera/photo', 'permit/status proof', 'field note', 'document'],
    sourceMatrixRows: ['S08 electrical systems match approved permit scope', 'S08 clearances from buildings for electrical utility equipment', 'S08 fire protection of wiring for emergency systems'],
    reason: 'Current corrected S10 is electrical; service readiness includes permit scope plus observable service/grounding conditions before concealment or energization.',
    launchPriority: 'P0',
    implementationStatus: 'ready_for_sprint_02b_ui_copy',
    mismatch: 'Pro source warned S10 was stale building-envelope content; current app has corrected electrical rows.',
    professionalAhjReviewQuestion: 'Which permit/status proof should come from Technical Safety BC versus AHJ records?',
  },
  {
    stageId: 'S10',
    itemCode: 'S10-02',
    itemLabel: 'Branch Circuit Rough-In',
    proMatrixClasses: ['A'],
    reconciledClass: 'A',
    evidenceTypes: ['camera/photo', 'field note'],
    sourceMatrixRows: ['S08 fire protection of wiring for emergency systems', 'Launch-critical: concealed rough-in work'],
    reason: 'Branch wiring support/protection and box rough-in are concealed by wall closure.',
    launchPriority: 'P0',
    implementationStatus: 'ready_for_sprint_02b_ui_copy',
    mismatch: 'Uses current corrected S10 electrical row, not stale Pro S10 envelope row.',
    professionalAhjReviewQuestion: 'Should evidence be required for all rough wiring or only protected/life-safety locations?',
  },
  {
    stageId: 'S10',
    itemCode: 'S10-03',
    itemLabel: 'Life Safety, Specialty Circuits, and Pre-Test Readiness',
    proMatrixClasses: ['A', 'D'],
    reconciledClass: 'A',
    evidenceTypes: ['camera/photo', 'field note', 'document'],
    sourceMatrixRows: ['S08 functional testing of electrical fire emergency systems', 'S08 fire protection of wiring for emergency systems', 'Professional-review queue: scope/applicability group'],
    reason: 'Life-safety and specialty circuits are concealed or scope-conditional; current row already limits evidence to where needed.',
    launchPriority: 'P0',
    implementationStatus: 'requires_professional_ahj_review',
    mismatch: 'Uses current corrected S10 electrical row, not stale Pro S10 envelope row.',
    professionalAhjReviewQuestion: 'Which specialty systems should be conditional visibility instead of N/A?',
  },
  {
    stageId: 'S10',
    itemCode: 'S10-04',
    itemLabel: 'Electrical Inspection and Documentation Closeout',
    proMatrixClasses: ['A', 'C'],
    reconciledClass: 'A',
    evidenceTypes: ['permit/status proof', 'document', 'field note'],
    sourceMatrixRows: ['Launch-critical: permit/status gates', 'S08 electrical systems match approved permit scope'],
    reason: 'Electrical closeout is a formal inspection/status gate and should be document/status evidence, not generic photos.',
    launchPriority: 'P0',
    implementationStatus: 'requires_template_model_change',
    mismatch: 'Uses current corrected S10 electrical closeout row; Pro packet had stale S10 title/content warning.',
    professionalAhjReviewQuestion: 'Which Technical Safety BC certificates/declarations should be accepted?',
  },
  {
    stageId: 'S11',
    itemCode: 'S11-01',
    itemLabel: 'Mechanical Permit and Equipment Rough-In',
    proMatrixClasses: ['C', 'A'],
    reconciledClass: 'A',
    evidenceTypes: ['camera/photo', 'permit/status proof', 'field note', 'document'],
    sourceMatrixRows: ['S06 mechanical systems match approved permit scope', 'S06 duct support, clearances, and fire separation continuity'],
    reason: 'Current corrected S11 is mechanical/gas; equipment rough-in combines permit scope and concealed/support/clearance observations.',
    launchPriority: 'P0',
    implementationStatus: 'ready_for_sprint_02b_ui_copy',
    mismatch: 'Pro source warned S11 was stale insulation content; current app has corrected mechanical/gas rows.',
    professionalAhjReviewQuestion: 'Which equipment/heat-load documents should remain optional versus required?',
  },
  {
    stageId: 'S11',
    itemCode: 'S11-02',
    itemLabel: 'Gas Piping, Venting, and Combustion',
    proMatrixClasses: ['A'],
    reconciledClass: 'A',
    evidenceTypes: ['camera/photo', 'test result', 'document', 'field note'],
    sourceMatrixRows: ['S06 gas line pressure test completed and documented', 'S06 combustion air and venting requirements met'],
    reason: 'Gas piping, venting, and pressure tests are safety-critical and often concealed.',
    launchPriority: 'P0',
    implementationStatus: 'ready_for_sprint_02b_ui_copy',
    mismatch: 'Uses current corrected S11 mechanical/gas row, not stale Pro S11 insulation row.',
    professionalAhjReviewQuestion: 'Should contractor pressure test records be mandatory before pass or before seal?',
  },
  {
    stageId: 'S11',
    itemCode: 'S11-03',
    itemLabel: 'Ventilation, Exhaust, Duct Coordination, and Fire Assembly Coordination',
    proMatrixClasses: ['A'],
    reconciledClass: 'A',
    evidenceTypes: ['camera/photo', 'field note', 'manufacturer/spec document'],
    sourceMatrixRows: ['S06 fire dampers at rated assemblies', 'S06 exhaust fan ducting to exterior', 'S06 duct support, clearances, and fire separation continuity'],
    reason: 'Ducts, exhaust routing, dampers, and firestopping are concealed or hard to verify after enclosure.',
    launchPriority: 'P0',
    implementationStatus: 'ready_for_sprint_02b_ui_copy',
    mismatch: 'Uses current corrected S11 mechanical/gas row, not stale Pro S11 insulation row.',
    professionalAhjReviewQuestion: 'Should damper schedules be document evidence where rated assemblies are involved?',
  },
  {
    stageId: 'S11',
    itemCode: 'S11-04',
    itemLabel: 'Mechanical and Gas Inspection Closeout',
    proMatrixClasses: ['A', 'C'],
    reconciledClass: 'A',
    evidenceTypes: ['permit/status proof', 'document', 'test result', 'field note'],
    sourceMatrixRows: ['Launch-critical: test-result or formal document evidence', 'S06 gas line pressure test completed and documented'],
    reason: 'Mechanical/gas closeout is a formal inspection/status gate with certificate/declaration evidence.',
    launchPriority: 'P0',
    implementationStatus: 'requires_template_model_change',
    mismatch: 'Uses current corrected S11 closeout row; Pro packet had stale S11 title/content warning.',
    professionalAhjReviewQuestion: 'Which TSBC gas documents and AHJ mechanical records are acceptable?',
  },
  {
    stageId: 'S12',
    itemCode: 'S12-01',
    itemLabel: 'Thermal Insulation and Continuity',
    proMatrixClasses: ['A'],
    reconciledClass: 'A',
    evidenceTypes: ['camera/photo', 'manufacturer/spec document', 'field note'],
    sourceMatrixRows: ['S11 insulation R-values meet energy code requirements', 'S11 rim joist insulation and air sealing', 'S11 attic insulation baffles installed'],
    reason: 'Current corrected S12 is insulation/energy; insulation and product values are concealed by drywall.',
    launchPriority: 'P0',
    implementationStatus: 'ready_for_sprint_02b_ui_copy',
    mismatch: 'Pro source warned S12 was stale drywall/interior content; current app has corrected insulation rows.',
    professionalAhjReviewQuestion: 'Should product label photos be mandatory where R-values are not visible later?',
  },
  {
    stageId: 'S12',
    itemCode: 'S12-02',
    itemLabel: 'Air Barrier, Vapour Control, and Penetrations',
    proMatrixClasses: ['A'],
    reconciledClass: 'A',
    evidenceTypes: ['camera/photo', 'video', 'manufacturer/spec document', 'field note'],
    sourceMatrixRows: ['S11 vapour barrier continuity', 'S11 air sealing at electrical boxes and penetrations', 'S10 air barrier continuity confirmed'],
    reason: 'Air/vapour barrier and penetration sealing are concealed and high-dispute energy/enclosure evidence points.',
    launchPriority: 'P0',
    implementationStatus: 'ready_for_sprint_02b_ui_copy',
    mismatch: 'Uses current corrected S12 insulation/energy row, not stale Pro S12 drywall row.',
    professionalAhjReviewQuestion: 'Should seams/laps and penetration sealing be separate prompts?',
  },
  {
    stageId: 'S12',
    itemCode: 'S12-03',
    itemLabel: 'Energy Documentation and Compliance Path',
    proMatrixClasses: ['A', 'E'],
    reconciledClass: 'A',
    evidenceTypes: ['document', 'test result', 'professional assurance document', 'field note'],
    sourceMatrixRows: ['Launch-critical: test-result or formal document evidence', 'S11 thermal bridging at intersecting assemblies addressed'],
    reason: 'Energy path, modeling, and testing are formal document/status evidence rather than photo-only observations.',
    launchPriority: 'P0',
    implementationStatus: 'requires_template_model_change',
    mismatch: 'Uses current corrected S12 energy row; Pro packet had stale S12 title/content warning.',
    professionalAhjReviewQuestion: 'Which energy-adviser or blower-door documents are mandatory by compliance path?',
  },
  {
    stageId: 'S12',
    itemCode: 'S12-04',
    itemLabel: 'Insulation Inspection and Energy Closeout',
    proMatrixClasses: ['A'],
    reconciledClass: 'A',
    evidenceTypes: ['permit/status proof', 'document', 'test result', 'professional assurance document'],
    sourceMatrixRows: ['Launch-critical: permit/status or formal document evidence', 'S15 Schedules C-A and C-B or equivalent letters of assurance'],
    reason: 'Energy closeout and insulation inspection status are formal closeout/document evidence.',
    launchPriority: 'P0',
    implementationStatus: 'requires_template_model_change',
    mismatch: 'Uses current corrected S12 closeout row; Pro packet had stale S12 title/content warning.',
    professionalAhjReviewQuestion: 'Should AHJ acceptance status be modeled separately from uploaded documents?',
  },
  {
    stageId: 'S13',
    itemCode: 'S13-01',
    itemLabel: 'Fire Separation, Rated Assemblies, and Sound Separation',
    proMatrixClasses: ['A'],
    reconciledClass: 'A',
    evidenceTypes: ['camera/photo', 'manufacturer/spec document', 'field note'],
    sourceMatrixRows: ['S12 fire-rated assemblies correctly constructed', 'S12 fire-rated penetration firestopping', 'S12 suite-to-suite sound insulation'],
    reason: 'Current corrected S13 is interior completion; rated assemblies and sound separations are concealed by finishes.',
    launchPriority: 'P0',
    implementationStatus: 'ready_for_sprint_02b_ui_copy',
    mismatch: 'Pro source warned S13 was stale life-safety content; current app has corrected interior rows.',
    professionalAhjReviewQuestion: 'Should ULC assembly references be structured for rated assemblies?',
  },
  {
    stageId: 'S13',
    itemCode: 'S13-02',
    itemLabel: 'Interior Wall Substrate, Wet-Area, and Concealed Backing',
    proMatrixClasses: ['A'],
    reconciledClass: 'A',
    evidenceTypes: ['camera/photo', 'manufacturer/spec document', 'field note'],
    sourceMatrixRows: ['S12 shaft wall and service chase construction', 'Launch-critical: concealed work'],
    reason: 'Wet-area substrate, waterproofing preparation, and backing are concealed by finish materials.',
    launchPriority: 'P0',
    implementationStatus: 'ready_for_sprint_02b_ui_copy',
    mismatch: 'Uses current corrected S13 interior row, not stale Pro S13 life-safety row.',
    professionalAhjReviewQuestion: 'Should waterproofing membrane data sheets be mandatory only when nonstandard systems are used?',
  },
  {
    stageId: 'S13',
    itemCode: 'S13-03',
    itemLabel: 'Interior Life Safety and Egress Readiness',
    proMatrixClasses: ['A', 'E'],
    reconciledClass: 'A',
    evidenceTypes: ['camera/photo', 'video', 'field note', 'document'],
    sourceMatrixRows: ['S13 emergency lighting and exit signs functional', 'S13 smoke and CO detector placement', 'S13 means of egress complete and unobstructed'],
    reason: 'Interior egress/fire-door/alarm readiness includes visible but occupancy-critical life-safety conditions.',
    launchPriority: 'P0',
    implementationStatus: 'ready_for_sprint_02b_ui_copy',
    mismatch: 'Current row combines corrected interior and final life-safety concepts.',
    professionalAhjReviewQuestion: 'Should houses and Part 3 buildings use different evidence levels?',
  },
  {
    stageId: 'S13',
    itemCode: 'S13-04',
    itemLabel: 'Interior Finishes and Systems Trim',
    proMatrixClasses: ['E', 'B'],
    reconciledClass: 'E',
    evidenceTypes: ['camera/photo', 'field note', 'manufacturer/spec document'],
    sourceMatrixRows: ['S13 means of egress complete and unobstructed', 'Decision rules: visible conditions can be recommended'],
    reason: 'Interior trim/finish readiness is mostly visible and revisitable; evidence should support deficiencies or disputes rather than hard-gate every pass.',
    launchPriority: 'P1',
    implementationStatus: 'ready_for_sprint_02b_ui_copy',
    mismatch: 'No exact Pro row exists for current interior trim closeout container.',
    professionalAhjReviewQuestion: 'Which finish material flame-spread conditions should become document evidence?',
  },
  {
    stageId: 'S13',
    itemCode: 'S13-05',
    itemLabel: 'Accessibility, Adaptable Housing, and Interior Closeout',
    proMatrixClasses: ['E', 'D'],
    reconciledClass: 'E',
    evidenceTypes: ['camera/photo', 'field note', 'document'],
    sourceMatrixRows: ['S13 means of egress complete and unobstructed', 'Professional-review queue: scope/applicability group'],
    reason: 'Accessibility/adaptable housing may be scope-conditional; visible evidence is useful but requires template triggers before hard enforcement.',
    launchPriority: 'P1',
    implementationStatus: 'requires_professional_ahj_review',
    mismatch: 'Current row has broader adaptable-housing scope than Pro final-life-safety rows.',
    professionalAhjReviewQuestion: 'Which accessibility paths should elevate this row to required evidence?',
  },
  {
    stageId: 'S14',
    itemCode: 'S14-01',
    itemLabel: 'Exterior Cladding, Envelope, and Weather-Resistive Continuity',
    proMatrixClasses: ['A'],
    reconciledClass: 'A',
    evidenceTypes: ['camera/photo', 'manufacturer/spec document', 'field note'],
    sourceMatrixRows: ['S10 weather-resistant barrier continuity at penetrations', 'S10 cladding drainage plane and ventilation gap', 'S04 weather-resistant barrier installed'],
    reason: 'Cladding/envelope continuity includes concealed rainscreen and penetration details.',
    launchPriority: 'P0',
    implementationStatus: 'ready_for_sprint_02b_ui_copy',
    professionalAhjReviewQuestion: 'Should exterior closeout require both broad elevation and close-up transition evidence?',
  },
  {
    stageId: 'S14',
    itemCode: 'S14-02',
    itemLabel: 'Exterior Stairs, Decks, Guards, and Handrails',
    proMatrixClasses: ['E'],
    reconciledClass: 'E',
    evidenceTypes: ['camera/photo', 'field note'],
    sourceMatrixRows: ['Decision rules: likely dispute record', 'S13 means of egress complete and unobstructed'],
    reason: 'Exterior guards and stairs are visible and revisitable; evidence is recommended for disputes and deficiencies.',
    launchPriority: 'P1',
    implementationStatus: 'requires_professional_ahj_review',
    mismatch: 'No exact Pro row exists for current exterior guard/deck container.',
    professionalAhjReviewQuestion: 'Should elevated decks/guards trigger required photo evidence before pass?',
  },
  {
    stageId: 'S14',
    itemCode: 'S14-03',
    itemLabel: 'Site Grading, Drainage, and Stormwater Control',
    proMatrixClasses: ['E', 'A'],
    reconciledClass: 'A',
    evidenceTypes: ['camera/photo', 'field note', 'permit/status proof', 'document'],
    sourceMatrixRows: ['S14 grade slopes away from foundation', 'S14 swales and drainage channels functional', 'S14 stormwater management compliant with municipal requirements'],
    reason: 'The active row combines visible grading with municipal stormwater compliance; the stormwater compliance component supports A.',
    launchPriority: 'P0',
    implementationStatus: 'requires_template_model_change',
    professionalAhjReviewQuestion: 'Should municipal stormwater sign-off be a separate status field from visible grading photos?',
  },
  {
    stageId: 'S14',
    itemCode: 'S14-04',
    itemLabel: 'Site Access, Servicing, Fire Authority Requirements, and Exterior Systems',
    proMatrixClasses: ['C', 'A'],
    reconciledClass: 'A',
    evidenceTypes: ['permit/status proof', 'document', 'camera/photo', 'field note'],
    sourceMatrixRows: ['S14 retaining walls permitted and inspected', 'S15 required agency reviews complete', 'S14 stormwater management compliant with municipal requirements'],
    reason: 'Servicing, fire authority, and exterior system readiness include agency/status gates and potentially cannot-proceed conditions.',
    launchPriority: 'P0',
    implementationStatus: 'requires_template_model_change',
    professionalAhjReviewQuestion: 'Which fire authority and servicing statuses should be structured instead of uploaded?',
  },
  {
    stageId: 'S14',
    itemCode: 'S14-05',
    itemLabel: 'Landscaping, Site Restoration, and Final Exterior Closeout',
    proMatrixClasses: ['E', 'B'],
    reconciledClass: 'E',
    evidenceTypes: ['camera/photo', 'field note', 'document'],
    sourceMatrixRows: ['S14 erosion and sediment controls removed or stabilized', 'S15 permit terms and outstanding deficiencies resolved'],
    reason: 'Site restoration is usually visible; evidence becomes important for deficiencies or closeout disputes.',
    launchPriority: 'P1',
    implementationStatus: 'ready_for_sprint_02b_ui_copy',
    professionalAhjReviewQuestion: 'Should development-permit landscaping or arborist conditions elevate this row to A?',
  },
  {
    stageId: 'S15',
    itemCode: 'S15-01',
    itemLabel: 'Life-Safety Systems Final Verification',
    proMatrixClasses: ['A'],
    reconciledClass: 'A',
    evidenceTypes: ['test result', 'document', 'camera/photo', 'video'],
    sourceMatrixRows: ['S13 fire alarm system functional test completed', 'S13 emergency lighting and exit signs functional', 'S13 sprinkler system final acceptance test'],
    reason: 'Final life-safety systems include formal commissioning/testing and occupancy-critical functional evidence.',
    launchPriority: 'P0',
    implementationStatus: 'ready_for_sprint_02b_ui_copy',
    mismatch: 'Current S15-01 is not Pro S15.1; Pro S15.1 remains system-state logic in SYSTEM_STATE_EVIDENCE_CONTROLS.',
    professionalAhjReviewQuestion: 'Which acceptance reports should be mandatory before final stage pass?',
  },
  {
    stageId: 'S15',
    itemCode: 'S15-02',
    itemLabel: 'Prior-Stage Deficiency Resolution and Final Trade Confirmations',
    proMatrixClasses: ['B', 'C'],
    reconciledClass: 'B',
    evidenceTypes: ['field note', 'document', 'permit/status proof'],
    sourceMatrixRows: ['S15 permit terms and outstanding deficiencies resolved', 'S15 final inspection passed or ready for authority review'],
    reason: 'Evidence is most important where deficiencies or trade confirmations remain unresolved; routine pass should reflect system state where possible.',
    launchPriority: 'P0',
    implementationStatus: 'requires_template_model_change',
    professionalAhjReviewQuestion: 'Can prior-stage deficiency closure be system-derived instead of upload-driven?',
  },
  {
    stageId: 'S15',
    itemCode: 'S15-03',
    itemLabel: 'Professional Assurance, Closeout Documents, and Final Vero Evidence Package',
    proMatrixClasses: ['A'],
    reconciledClass: 'A',
    evidenceTypes: ['professional assurance document', 'document', 'permit/status proof'],
    sourceMatrixRows: ['S15 Schedules C-A and C-B or equivalent letters of assurance'],
    reason: 'Professional assurance and closeout documents are formal documentary evidence required where applicable.',
    launchPriority: 'P0',
    implementationStatus: 'requires_professional_ahj_review',
    professionalAhjReviewQuestion: 'Should pass require uploaded PDFs or verified receipt/status metadata?',
  },
  {
    stageId: 'S15',
    itemCode: 'S15-04',
    itemLabel: 'AHJ Final Approval Status and Occupancy Permit Documentation',
    proMatrixClasses: ['A', 'C'],
    reconciledClass: 'A',
    evidenceTypes: ['permit/status proof', 'document', 'field note'],
    sourceMatrixRows: ['S15 final inspection passed or ready for authority review', 'S15 occupancy permit identified for commercial or multi-unit residential VBBL only', 'S15 issued permits in place before occupancy application VBBL only'],
    reason: 'AHJ final approval and occupancy documentation are administrative status gates; Vero records readiness/status and does not issue occupancy.',
    launchPriority: 'P0',
    implementationStatus: 'requires_template_model_change',
    professionalAhjReviewQuestion: 'Should ready-for-authority-review be separated from final approval/occupancy issued?',
  },
]

export const INSPECTION_EVIDENCE_POLICY_BY_CODE = new Map(
  INSPECTION_EVIDENCE_POLICY.map(entry => [entry.itemCode, entry]),
)
