import type {
  Project,
  InspectorProfile,
  BuilderProfile,
  InspectionJob,
  ActiveInspection,
  CompletedInspection,
  InspectionStage,
  DispatchPricing,
  EscrowRecord,
} from './types'
import { DISPATCH_PRICING as SHARED_DISPATCH_PRICING } from '@/lib/pricing/config'

// ─── Inspection Stages (hardcoded per PRD) ────────────────────────────────────

export const INSPECTION_STAGES: InspectionStage[] = [
  {
    id: 1,
    name: 'Site Survey & Excavation',
    shortName: 'Site Survey',
    description: 'Before concrete pour — verify site conditions and excavation compliance',
    items: [
      { id: 's1-1', label: 'Property Line Verification', description: 'Confirm survey pins and legal boundaries match approved plans' },
      { id: 's1-2', label: 'Setback Compliance', description: 'Verify minimum setbacks from property lines per zoning bylaw' },
      { id: 's1-3', label: 'Soil Bearing Capacity', description: 'Confirm soil report matches actual conditions at excavation depth' },
      { id: 's1-4', label: 'Cut Elevation', description: 'Verify excavation depth matches engineered drawings ± 50mm' },
      { id: 's1-5', label: 'Sediment & Erosion Control', description: 'Silt fencing, inlet protection, and rock pads installed per SWPPP' },
      { id: 's1-6', label: 'Tree Protection', description: 'Tree protection fencing at drip line; no equipment within zone' },
      { id: 's1-7', label: 'Safety Shoring', description: 'Shoring/benching meets WorkSafeBC requirements for excavation depth' },
    ],
  },
  {
    id: 2,
    name: 'Foundation Pour',
    shortName: 'Foundation',
    description: 'Pre-pour inspection — verify formwork and reinforcement before concrete',
    items: [
      { id: 's2-1', label: 'Formwork Placement', description: 'Forms plumb, square, properly braced; no gaps or deflection risk' },
      { id: 's2-2', label: 'Reinforcing Steel (Rebar)', description: 'Size, spacing, lap lengths, and hooks match structural drawings' },
      { id: 's2-3', label: 'Clearance to Earth', description: 'Minimum 75mm cover to earth; 50mm to forms per CSA A23.1' },
      { id: 's2-4', label: 'Ufer Ground', description: 'Grounding electrode embedded in footing per BC Electrical Code' },
      { id: 's2-5', label: 'Void Forms', description: 'Cardboard void forms installed under grade beams on expansive soils' },
      { id: 's2-6', label: 'Anchor Bolts/Hold-downs', description: 'Location, embedment, and projection match shear wall schedule' },
      { id: 's2-7', label: 'Cleanliness', description: 'Excavation free of standing water, loose soil, and debris before pour' },
      { id: 's2-8', label: 'Sleeve Penetrations', description: 'All utility sleeves properly sized, located, and temporarily capped' },
    ],
  },
  {
    id: 3,
    name: 'Framing & Lock-up',
    shortName: 'Framing',
    description: 'Rough-in inspection — verify structural framing before sheathing',
    items: [
      { id: 's3-1', label: 'Load Path Verification', description: 'Continuous load path from roof to foundation; posts, beams, columns aligned' },
      { id: 's3-2', label: 'Shear Wall Nailing', description: 'Nail size, spacing, and blocked diaphragm per shear wall schedule' },
      { id: 's3-3', label: 'Fire Blocking', description: 'Fire blocks installed at floor lines, soffits, and concealed spaces' },
      { id: 's3-4', label: 'Rough-In Pass (MEP)', description: 'Plumbing, electrical, and mechanical rough-in signed off by respective trades' },
      { id: 's3-5', label: 'Window & Door Flashing', description: 'Pan flashing, sill tape, and head flashing installed per window manufacturer spec' },
      { id: 's3-6', label: 'Roof Truss Anchors', description: 'Hurricane ties and uplift connectors per truss engineering at every truss' },
      { id: 's3-7', label: 'Stair Geometry', description: 'Rise/run uniformity ± 3/8"; total rise and run per BCBC 9.8' },
      { id: 's3-8', label: 'Moisture Content', description: 'Framing lumber ≤ 19% MC verified with calibrated moisture meter' },
    ],
  },
  {
    id: 4,
    name: 'Insulation & Vapor Barrier',
    shortName: 'Insulation',
    description: 'Thermal and moisture control inspection before drywall',
    items: [
      { id: 's4-1', label: 'R-Value Verification', description: 'Insulation type and depth achieves required R-values per BCBC energy schedule' },
      { id: 's4-2', label: 'Vapor Barrier Continuity', description: '6-mil poly lapped 300mm at all seams; sealed at penetrations and top/bottom plates' },
      { id: 's4-3', label: 'Acoustic Sealant', description: 'Acoustical sealant applied at perimeter of vapor barrier before compression' },
      { id: 's4-4', label: 'Electrical Box Sealing', description: 'Airtight electrical boxes or poly dams sealed with acoustical sealant' },
      { id: 's4-5', label: 'Baffles/Ventilation', description: 'Ventilation baffles maintain 63mm clear airway from eave to ridge' },
      { id: 's4-6', label: 'Spray Foam Curing', description: 'Closed-cell SPF fully cured (≥ 24h); no soft spots; thickness per specs' },
      { id: 's4-7', label: 'Plumbing Wall Protection', description: 'Nail plates on all pipes within 38mm of stud face per BCPC' },
    ],
  },
  {
    id: 5,
    name: 'Final Occupancy Permit',
    shortName: 'Final',
    description: 'Final inspection before occupancy permit issuance',
    items: [
      { id: 's5-1', label: 'Life Safety Systems', description: 'Smoke alarms, CO detectors, and interconnected wiring per BCBC 9.10' },
      { id: 's5-2', label: 'Handrails & Guards', description: 'Height, spacing, and graspability per BCBC 9.8.7; no gaps > 100mm' },
      { id: 's5-3', label: 'Plumbing Fixtures', description: 'All fixtures installed, water supply and drain tested; no leaks' },
      { id: 's5-4', label: 'Ventilation Balancing', description: 'HRV/ERV commissioned; exhaust flows balanced per ASHRAE 62.2' },
      { id: 's5-5', label: 'Address Display', description: 'Civic address visible from street; minimum 100mm numerals' },
      { id: 's5-6', label: 'Final Grading', description: 'Positive drainage away from foundation; 2% slope within 1.8m' },
      { id: 's5-7', label: 'Door Blower Test', description: 'Airtightness ≤ 2.5 ACH@50Pa per BC Step Code target' },
      { id: 's5-8', label: 'Trade Sign-offs', description: 'All sub-trade final inspection certificates received and filed' },
    ],
  },
]

// ─── Dispatch Pricing ─────────────────────────────────────────────────────────

export const DISPATCH_PRICING: DispatchPricing[] = SHARED_DISPATCH_PRICING

// ─── Builder Profile ──────────────────────────────────────────────────────────

export const MOCK_BUILDER: BuilderProfile = {
  id: 'builder-001',
  companyName: 'Coastal Developments Inc.',
  contactName: 'Marcus Webb',
  email: 'marcus@coastaldevelopments.ca',
  phone: '604-555-0142',
  activeProjects: 4,
}

// ─── Inspector Profile ────────────────────────────────────────────────────────

export const MOCK_INSPECTOR: InspectorProfile = {
  id: 'inspector-001',
  firstName: 'Sarah',
  lastName: 'Chen',
  name: 'Dr. Sarah Chen, P.Eng',
  licenseNumber: 'BC-ENG-29847',
  discipline: ['structural', 'geotech'],
  region: ['vancouver', 'burnaby', 'richmond'],
  rating: 4.97,
  completedInspections: 312,
  photoUrl: '/inspector-avatar.jpg',
  isAvailable: true,
  currentLocation: {
    lat: 49.2634,
    lng: -123.1382,
    accuracy: 3,
    timestamp: new Date().toISOString(),
    deviceId: 'iphone-15-pro-A1',
  },
  earningsToday: 590,
  earningsWeek: 2655,
  earningsMonth: 10620,
}

// ─── Projects ────────────────────────────────────────────────────────────────

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-001',
    builderId: 'builder-001',
    name: 'Kitsilano Infill Duplex',
    address: '2847 Cornwall Ave',
    city: 'Vancouver, BC',
    permitNumber: 'BP-2024-04821',
    currentStage: 3,
    status: 'in_progress',
    gpsCoord: {
      lat: 49.2727,
      lng: -123.1588,
      accuracy: 2,
      timestamp: '2026-02-23T14:00:00Z',
      deviceId: 'site-gps-001',
    },
    stages: [
      { stageNumber: 1, stageName: 'Site Survey & Excavation', status: 'pass', completedAt: '2026-01-15T16:30:00Z', inspectorId: 'inspector-001', scheduleC_B: '/mock-pdf' },
      { stageNumber: 2, stageName: 'Foundation Pour', status: 'pass', completedAt: '2026-01-28T15:45:00Z', inspectorId: 'inspector-001', scheduleC_B: '/mock-pdf' },
      { stageNumber: 3, stageName: 'Framing & Lock-up', status: 'in_progress', inspectorId: 'inspector-001' },
      { stageNumber: 4, stageName: 'Insulation & Vapor Barrier', status: 'pending' },
      { stageNumber: 5, stageName: 'Final Occupancy Permit', status: 'pending' },
    ],
    photos: [
      { id: 'photo-001', url: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800', thumbnailUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=200', takenAt: '2026-01-28T10:00:00Z', pins: [] },
      { id: 'photo-002', url: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=800', thumbnailUrl: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=200', takenAt: '2026-01-28T10:15:00Z', pins: [
        { id: 'pin-001', x: 45, y: 60, note: 'Clearance to earth insufficient — needs 25mm more cover', photoId: 'photo-002' }
      ]},
    ],
    createdAt: '2026-01-05T09:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'proj-002',
    builderId: 'builder-001',
    name: 'Mount Pleasant Laneway House',
    address: '155 E 10th Ave',
    city: 'Vancouver, BC',
    permitNumber: 'BP-2024-05103',
    currentStage: 5,
    status: 'pending',
    gpsCoord: {
      lat: 49.2609,
      lng: -123.1007,
      accuracy: 3,
      timestamp: '2026-02-22T09:00:00Z',
      deviceId: 'site-gps-002',
    },
    stages: [
      { stageNumber: 1, stageName: 'Site Survey & Excavation', status: 'pass', completedAt: '2025-10-12T14:00:00Z', inspectorId: 'inspector-002', scheduleC_B: '/mock-pdf' },
      { stageNumber: 2, stageName: 'Foundation Pour', status: 'pass', completedAt: '2025-11-04T16:00:00Z', inspectorId: 'inspector-001', scheduleC_B: '/mock-pdf' },
      { stageNumber: 3, stageName: 'Framing & Lock-up', status: 'pass', completedAt: '2025-12-03T15:00:00Z', inspectorId: 'inspector-003', scheduleC_B: '/mock-pdf' },
      { stageNumber: 4, stageName: 'Insulation & Vapor Barrier', status: 'pass', completedAt: '2026-01-17T13:30:00Z', inspectorId: 'inspector-001', scheduleC_B: '/mock-pdf' },
      { stageNumber: 5, stageName: 'Final Occupancy Permit', status: 'pending' },
    ],
    photos: [
      { id: 'photo-003', url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800', thumbnailUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=200', takenAt: '2026-01-17T09:30:00Z', pins: [] },
    ],
    createdAt: '2025-09-20T09:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'proj-003',
    builderId: 'builder-001',
    name: 'Burnaby Strathcona Condo',
    address: '4521 Kingsway',
    city: 'Burnaby, BC',
    permitNumber: 'BP-2025-00342',
    currentStage: 1,
    status: 'pass',
    gpsCoord: {
      lat: 49.2388,
      lng: -123.0012,
      accuracy: 4,
      timestamp: '2026-02-20T11:00:00Z',
      deviceId: 'site-gps-003',
    },
    stages: [
      { stageNumber: 1, stageName: 'Site Survey & Excavation', status: 'pass', completedAt: '2026-02-20T15:00:00Z', inspectorId: 'inspector-002', scheduleC_B: '/mock-pdf' },
      { stageNumber: 2, stageName: 'Foundation Pour', status: 'pending' },
      { stageNumber: 3, stageName: 'Framing & Lock-up', status: 'pending' },
      { stageNumber: 4, stageName: 'Insulation & Vapor Barrier', status: 'pending' },
      { stageNumber: 5, stageName: 'Final Occupancy Permit', status: 'pending' },
    ],
    photos: [
      { id: 'photo-004', url: 'https://images.unsplash.com/photo-1590725121839-892b458a74fe?w=800', thumbnailUrl: 'https://images.unsplash.com/photo-1590725121839-892b458a74fe?w=200', takenAt: '2026-02-20T09:00:00Z', pins: [] },
    ],
    createdAt: '2026-02-01T09:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'proj-004',
    builderId: 'builder-001',
    name: 'Surrey Newton Townhomes',
    address: '13887 104 Ave',
    city: 'Surrey, BC',
    permitNumber: 'BP-2025-01879',
    currentStage: 2,
    status: 'fail',
    gpsCoord: {
      lat: 49.1875,
      lng: -122.8479,
      accuracy: 5,
      timestamp: '2026-02-18T14:00:00Z',
      deviceId: 'site-gps-004',
    },
    stages: [
      { stageNumber: 1, stageName: 'Site Survey & Excavation', status: 'pass', completedAt: '2026-01-22T12:00:00Z', inspectorId: 'inspector-003', scheduleC_B: '/mock-pdf' },
      { stageNumber: 2, stageName: 'Foundation Pour', status: 'fail', completedAt: '2026-02-18T16:00:00Z', inspectorId: 'inspector-002' },
      { stageNumber: 3, stageName: 'Framing & Lock-up', status: 'pending' },
      { stageNumber: 4, stageName: 'Insulation & Vapor Barrier', status: 'pending' },
      { stageNumber: 5, stageName: 'Final Occupancy Permit', status: 'pending' },
    ],
    photos: [
      { id: 'photo-005', url: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800', thumbnailUrl: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=200', takenAt: '2026-02-18T10:00:00Z', pins: [
        { id: 'pin-002', x: 30, y: 55, note: 'Rebar spacing 275mm — spec requires 200mm OC', photoId: 'photo-005' },
        { id: 'pin-003', x: 70, y: 40, note: 'Clearance to earth only 40mm — needs 75mm min', photoId: 'photo-005' },
      ]},
    ],
    createdAt: '2026-01-10T09:00:00Z',
    updatedAt: new Date().toISOString(),
  },
]

// ─── Inspector Job Queue ──────────────────────────────────────────────────────

// Helper to build a date string N days from now
function daysFromNow(n: number): string {
  const d = new Date(); d.setDate(d.getDate() + n)
  return d.toISOString().slice(0, 10)
}

export const MOCK_JOBS: InspectionJob[] = [
  {
    id: 'job-001',
    projectId: 'proj-ext-001',
    projectName: 'Yaletown High-Rise Podium',
    address: '1055 Homer St',
    city: 'Vancouver',
    permitNumber: 'BP-2024-09341',
    projectType: 'Mixed-Use High-Rise (12 storey)',
    stage: 2,
    stageName: 'Foundation Pour',
    dispatchTier: 'emergency',
    offeredRate: 590,
    estimatedDuration: 120,
    distance: 3.2,
    region: 'vancouver',
    requiredDiscipline: 'structural',
    status: 'live',
    requestedAt: new Date(Date.now() - 25 * 60000).toISOString(),
    escrowAmount: 590,
    availableSlots: [
      { date: daysFromNow(1), startTime: '08:00', endTime: '12:00' },
      { date: daysFromNow(1), startTime: '13:00', endTime: '17:00' },
      { date: daysFromNow(2), startTime: '09:00', endTime: '12:00' },
    ],
    builderName: 'Bosa Development Corp.',
    builderRating: 4.8,
    builderCompletedJobs: 47,
    builderNotes: 'Site foreman Marcus will meet you at the Hornby St gate. Hard hat and steel toes required on site. Rebar cage is complete — pre-pour concrete scheduled for tomorrow AM, time sensitive.',
    requiredGear: ['Hard hat (CSA)', 'Steel-toe boots', 'High-vis vest', 'Tape measure', 'Depth gauge'],
    isReinspection: false,
  },
  {
    id: 'job-002',
    projectId: 'proj-ext-002',
    projectName: 'Oakridge Laneway Infill',
    address: '6812 Ash St',
    city: 'Vancouver',
    permitNumber: 'BP-2025-03218',
    projectType: 'Laneway House (Single Family)',
    stage: 4,
    stageName: 'Insulation & Vapor Barrier',
    dispatchTier: 'priority',
    offeredRate: 443,
    estimatedDuration: 90,
    distance: 5.8,
    region: 'vancouver',
    requiredDiscipline: 'architectural',
    status: 'live',
    requestedAt: new Date(Date.now() - 45 * 60000).toISOString(),
    escrowAmount: 443,
    availableSlots: [
      { date: daysFromNow(2), startTime: '09:00', endTime: '12:00' },
      { date: daysFromNow(3), startTime: '10:00', endTime: '14:00' },
    ],
    builderName: 'Pacific Coast Custom Builds',
    builderRating: 4.6,
    builderCompletedJobs: 12,
    builderNotes: 'Access through back alley gate — code is 4821. Poly is fully installed, just need R-value sign-off and vapor barrier seam check.',
    requiredGear: ['Hard hat (CSA)', 'Moisture meter', 'Flashlight'],
    isReinspection: false,
  },
  {
    id: 'job-003',
    projectId: 'proj-ext-003',
    projectName: 'Burnaby Heights Single Family',
    address: '3847 Triumph St',
    city: 'Burnaby',
    permitNumber: 'BP-2025-01104',
    projectType: 'Single Family Residential',
    stage: 3,
    stageName: 'Framing & Lock-up',
    dispatchTier: 'standard',
    offeredRate: 295,
    estimatedDuration: 100,
    distance: 12.4,
    region: 'burnaby',
    requiredDiscipline: 'structural',
    status: 'live',
    requestedAt: new Date(Date.now() - 3 * 3600000).toISOString(),
    escrowAmount: 295,
    availableSlots: [
      { date: daysFromNow(3), startTime: '08:00', endTime: '11:00' },
      { date: daysFromNow(4), startTime: '09:00', endTime: '12:00' },
      { date: daysFromNow(5), startTime: '13:00', endTime: '17:00' },
    ],
    builderName: 'Altura Homes Ltd.',
    builderRating: 4.9,
    builderCompletedJobs: 29,
    builderNotes: 'This is a re-inspection. Shear wall nailing was flagged on first visit — corrected per engineer\'s direction. Please re-check SW corner panels specifically.',
    requiredGear: ['Hard hat (CSA)', 'Nail gauge', 'Tape measure', 'Ladder'],
    isReinspection: true,
    previousFailNotes: [
      'SW corner shear wall — nail spacing 4" OC, spec requires 3" OC at panel edges',
      'Missing fire blocking at stair soffit — not installed at time of first inspection',
    ],
  },
  {
    id: 'job-004',
    projectId: 'proj-ext-004',
    projectName: 'Richmond Riverport Industrial',
    address: '11291 Horseshoe Way',
    city: 'Richmond',
    permitNumber: 'BP-2025-00882',
    projectType: 'Industrial / Tilt-Up Warehouse',
    stage: 1,
    stageName: 'Site Survey & Excavation',
    dispatchTier: 'priority',
    offeredRate: 443,
    estimatedDuration: 110,
    distance: 18.7,
    region: 'richmond',
    requiredDiscipline: 'geotech',
    status: 'live',
    requestedAt: new Date(Date.now() - 90 * 60000).toISOString(),
    escrowAmount: 443,
    availableSlots: [
      { date: daysFromNow(2), startTime: '07:30', endTime: '11:00' },
      { date: daysFromNow(3), startTime: '08:00', endTime: '12:00' },
    ],
    builderName: 'Conwest Group',
    builderRating: 4.7,
    builderCompletedJobs: 63,
    builderNotes: 'Geotech report from EBA Engineering on file — will email PDF. Excavation is 4.2m deep, shoring in place. Confirm soil bearing matches report at 150 kPa.',
    requiredGear: ['Hard hat (CSA)', 'Steel-toe boots', 'High-vis vest', 'Soil probe', 'Safety harness'],
    isReinspection: false,
  },
  {
    id: 'job-005',
    projectId: 'proj-ext-005',
    projectName: 'Coquitlam Burke Mountain Semi',
    address: '3309 David Ave',
    city: 'Coquitlam',
    permitNumber: 'BP-2025-02771',
    projectType: 'Semi-Detached Residential (Duplex)',
    stage: 5,
    stageName: 'Final Occupancy Permit',
    dispatchTier: 'standard',
    offeredRate: 295,
    estimatedDuration: 150,
    distance: 28.1,
    region: 'coquitlam',
    requiredDiscipline: 'architectural',
    status: 'live',
    requestedAt: new Date(Date.now() - 5 * 3600000).toISOString(),
    escrowAmount: 295,
    availableSlots: [
      { date: daysFromNow(5), startTime: '09:00', endTime: '13:00' },
      { date: daysFromNow(6), startTime: '10:00', endTime: '14:00' },
    ],
    builderName: 'Wesbrook Homes',
    builderRating: 4.5,
    builderCompletedJobs: 8,
    builderNotes: 'Both units ready for final. HRV commissioned last week. Blower door test booked for same morning — please coordinate with HVAC tech on site (Jordan, 604-555-0188).',
    requiredGear: ['Hard hat (CSA)', 'CO detector tester', 'Smoke alarm tester'],
    isReinspection: false,
  },
  {
    id: 'job-006',
    projectId: 'proj-ext-006',
    projectName: 'Surrey Central Mixed-Use',
    address: '10090 152 St',
    city: 'Surrey',
    permitNumber: 'BP-2025-04490',
    projectType: 'Mixed-Use (Retail + 6 Storey Residential)',
    stage: 2,
    stageName: 'Foundation Pour',
    dispatchTier: 'emergency',
    offeredRate: 590,
    estimatedDuration: 130,
    distance: 22.5,
    region: 'surrey',
    requiredDiscipline: 'structural',
    status: 'live',
    requestedAt: new Date(Date.now() - 10 * 60000).toISOString(),
    escrowAmount: 590,
    availableSlots: [
      { date: daysFromNow(1), startTime: '07:00', endTime: '11:00' },
      { date: daysFromNow(1), startTime: '12:00', endTime: '16:00' },
    ],
    builderName: 'Anthem Properties',
    builderRating: 4.9,
    builderCompletedJobs: 94,
    builderNotes: 'Concrete is ordered for tomorrow morning 6 AM — MUST have sign-off today or pour is delayed 48h. Rebar cage complete, formwork braced. This is urgent.',
    requiredGear: ['Hard hat (CSA)', 'Steel-toe boots', 'High-vis vest', 'Rebar gauge', 'Tape measure', 'Depth gauge'],
    isReinspection: false,
  },
]

// ─── Active Inspection (for /inspector/inspection/[id]) ─────────────────────

export const MOCK_ACTIVE_INSPECTION: ActiveInspection = {
  id: 'insp-active-001',
  jobId: 'job-001',
  inspectorId: 'inspector-001',
  projectId: 'proj-ext-001',
  projectName: 'Yaletown High-Rise Podium',
  address: '1055 Homer St, Vancouver',
  stage: 2,
  stageName: 'Foundation Pour',
  permitNumber: 'BP-2024-04821',
  startedAt: new Date(Date.now() - 34 * 60000).toISOString(),
  timerSeconds: 34 * 60,
  checklistState: {},
  preFlightPhotos: [],
  gpsAtArrival: {
    lat: 49.2742,
    lng: -123.1211,
    accuracy: 2,
    timestamp: new Date(Date.now() - 34 * 60000).toISOString(),
    deviceId: 'iphone-15-pro-A1',
  },
  digitalSealApplied: false,
  offlineQueue: [],
}

// ─── Completed Inspections (Auditor Vault) ───────────────────────────────────

export const MOCK_COMPLETED_INSPECTIONS: CompletedInspection[] = [
  {
    id: 'completed-001',
    permitNumber: 'BP-2024-04821',
    address: '2847 Cornwall Ave',
    city: 'Vancouver, BC',
    stage: 2,
    stageName: 'Foundation Pour',
    inspectorName: 'Dr. Sarah Chen, P.Eng',
    inspectorLicense: 'BC-ENG-29847',
    status: 'pass',
    completedAt: '2026-01-28T15:45:00Z',
    gpsAtArrival: {
      lat: 49.2727,
      lng: -123.1588,
      accuracy: 2,
      timestamp: '2026-01-28T13:08:22Z',
      deviceId: 'iphone-15-pro-A1',
    },
    cryptoHash: 'sha256:a3f8c2d4e7b1908f5a2c6d8e3f1b4a7c9d2e5f8b1c4a7d0e3f6b9c2d5e8f1b4',
    deviceId: 'iphone-15-pro-A1',
    scheduleC_B_url: '/mock-schedule-cb.pdf',
    photos: [
      { id: 'aud-photo-001', url: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800', thumbnailUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=200', takenAt: '2026-01-28T13:15:00Z', pins: [], gps: { lat: 49.2727, lng: -123.1588, accuracy: 3, timestamp: '2026-01-28T13:15:00Z', deviceId: 'iphone-15-pro-A1' } },
    ],
    checklistSummary: { total: 8, passed: 8, failed: 0, na: 0 },
  },
  {
    id: 'completed-002',
    permitNumber: 'BP-2025-01879',
    address: '13887 104 Ave',
    city: 'Surrey, BC',
    stage: 2,
    stageName: 'Foundation Pour',
    inspectorName: 'James Nakamura, P.Eng',
    inspectorLicense: 'BC-ENG-31422',
    status: 'fail',
    completedAt: '2026-02-18T16:00:00Z',
    gpsAtArrival: {
      lat: 49.1875,
      lng: -122.8479,
      accuracy: 3,
      timestamp: '2026-02-18T14:02:11Z',
      deviceId: 'samsung-s24-ultra-B3',
    },
    cryptoHash: 'sha256:b7e2f5a8d1c4g7h0i3j6k9l2m5n8o1p4q7r0s3t6u9v2w5x8y1z4a7b0c3d6e9',
    deviceId: 'samsung-s24-ultra-B3',
    scheduleC_B_url: '/mock-schedule-cb-fail.pdf',
    photos: [
      { id: 'aud-photo-002', url: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800', thumbnailUrl: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=200', takenAt: '2026-02-18T14:20:00Z', pins: [
        { id: 'aud-pin-001', x: 30, y: 55, note: 'Rebar spacing non-compliant', photoId: 'aud-photo-002' }
      ], gps: { lat: 49.1875, lng: -122.8479, accuracy: 4, timestamp: '2026-02-18T14:20:00Z', deviceId: 'samsung-s24-ultra-B3' } },
    ],
    checklistSummary: { total: 8, passed: 5, failed: 2, na: 1 },
  },
]

// ─── Escrow Records ───────────────────────────────────────────────────────────

export const MOCK_ESCROW: EscrowRecord[] = [
  {
    jobId: 'job-001',
    amount: 590,
    status: 'held',
    stripePaymentIntentId: 'pi_3OmK2sJKhQcA4vXf0QtzUhBp',
    heldAt: new Date(Date.now() - 25 * 60000).toISOString(),
  },
  {
    jobId: 'job-003',
    amount: 295,
    status: 'earned_pending_review',
    stripePaymentIntentId: 'pi_3OmK2sJKhQcA4vXf0QtzBnCq',
    heldAt: new Date(Date.now() - 3 * 3600000).toISOString(),
  },
  {
    jobId: 'job-005',
    amount: 295,
    status: 'disputed',
    stripePaymentIntentId: 'pi_3OmK2sJKhQcA4vXf0QtzDpEr',
    heldAt: new Date(Date.now() - 5 * 3600000).toISOString(),
  },
]
