import { buildScheduleCBPacketData, makePlaceholderEvidenceDataUri } from './scheduleCBPacketHelpers'
import type { ScheduleCBPacketSource } from './scheduleCBPacketTypes'

export const SAMPLE_SCHEDULE_CB_PACKET_SOURCE: ScheduleCBPacketSource = {
  report: {
    id: 'report-sample-001',
    assignmentId: 'assignment-sample-001',
    jobId: 'job-sample-001',
    inspectorId: 'inspector-sample-001',
    projectId: 'project-sample-001',
    projectName: 'Vero Mixed-Use Demonstration',
    address: '555 Cambie Street',
    city: 'Vancouver',
    region: 'BC',
    projectType: 'Mixed-use',
    currentStage: 15,
    stageCount: 15,
    jurisdictionName: 'City of Vancouver',
    ahjOverlayType: 'vancouver',
    ahjOverlayLabel: 'Vancouver Building By-law Overlay',
    overlaySnapshot: {
      type: 'vancouver',
      label: 'Vancouver Building By-law Overlay',
      jurisdictionName: 'City of Vancouver',
      signals: ['VBBL field review alignment', 'Letters of Assurance tracking'],
      summary: 'Applied Vancouver Building By-law overlay for final structural field review and occupancy packet generation.',
    },
    checklistSnapshot: [],
    status: 'sealed',
    sealApplied: true,
    sealReference: 'VERO-SEAL-2026-0001',
    sealPayload: {
      overallResult: 'pass',
      stageSignOffs: {
        '15': {
          stageNumber: 15,
          signedAt: '2026-04-11T16:21:00.000Z',
          latitude: 49.282732,
          longitude: -123.110471,
        },
      },
    },
    sealedAt: '2026-04-11T16:21:00.000Z',
    lastSavedAt: '2026-04-11T16:21:05.000Z',
    submittedAt: '2026-04-11T16:21:00.000Z',
    createdAt: '2026-04-11T15:00:00.000Z',
    updatedAt: '2026-04-11T16:21:05.000Z',
  },
  items: [
    {
      itemCode: 'S15-01',
      itemLabel: 'Life-Safety Systems Final Verification',
      responseNote: 'Smoke alarms, guards, egress, and fire separation confirmed at reviewed locations.',
      stageNumber: 15,
      stageName: 'Inspections, Final Approval, and Occupancy',
      inspectionStatus: 'Passed',
    },
    {
      itemCode: 'S15-02',
      itemLabel: 'Prior-Stage Deficiency Resolution and Final Trade Confirmations',
      responseNote: 'All prior deficiencies resolved. Trade confirmations uploaded.',
      stageNumber: 15,
      stageName: 'Inspections, Final Approval, and Occupancy',
      inspectionStatus: 'Passed',
    },
  ],
  documents: [
    {
      id: 'doc-sample-001',
      itemCode: 'S15-01',
      fileName: 'entry-canopy.jpg',
      storagePath: 'fixture://entry-canopy.jpg',
      mimeType: 'image/jpeg',
      createdAt: '2026-04-11T16:02:00.000Z',
      capturedAt: '2026-04-11T16:02:00.000Z',
      latitude: 49.282701,
      longitude: -123.110455,
      imageUrl: makePlaceholderEvidenceDataUri('Entry Canopy'),
    },
    {
      id: 'doc-sample-002',
      itemCode: 'S15-02',
      fileName: 'lobby-rail.jpg',
      storagePath: 'fixture://lobby-rail.jpg',
      mimeType: 'image/jpeg',
      createdAt: '2026-04-11T16:07:00.000Z',
      capturedAt: '2026-04-11T16:07:00.000Z',
      latitude: 49.282728,
      longitude: -123.110410,
      imageUrl: makePlaceholderEvidenceDataUri('Lobby Rail'),
    },
  ],
  officialFormOptions: {
    inspectorName: 'Alex Morgan',
    inspectorLicense: 'AIBC-12345',
    discipline: 'Architectural',
    firmName: 'Vero Field Review Partners',
    inspectorAddress: '200 Granville Street',
    inspectorAddressCont: 'Vancouver, BC V6C 1S4',
    inspectorContact: '604-555-0147 · alex.morgan@veropermit.ca',
    buildingPermitNumber: 'BP-2026-1842',
  },
  buildingPermitNumber: 'BP-2026-1842',
  exportMode: 'authority_facing',
  generatedAtIso: '2026-04-11T16:21:15.000Z',
  verificationId: 'VERO-PACKET-2026-0001',
}

export const SAMPLE_SCHEDULE_CB_PACKET_DATA = buildScheduleCBPacketData(SAMPLE_SCHEDULE_CB_PACKET_SOURCE)
