import type { PropertyProviderStatus } from "@/lib/property-review/types";

export const lowerMainlandAuditDate = "2026-09-29";

export const lowerMainlandJurisdictionIds = [
  "anmore",
  "belcarra",
  "bowen-island",
  "burnaby",
  "coquitlam",
  "delta",
  "langley-city",
  "langley-township",
  "lions-bay",
  "maple-ridge",
  "new-westminster",
  "north-vancouver-city",
  "north-vancouver-district",
  "pitt-meadows",
  "port-coquitlam",
  "port-moody",
  "richmond",
  "surrey",
  "vancouver",
  "west-vancouver",
  "white-rock",
  "metro-electoral-area-a",
  "tsawwassen-first-nation",
  "abbotsford",
  "chilliwack",
  "harrison-hot-springs",
  "hope",
  "kent",
  "mission",
  "fvrd-electoral-area",
  "first-nation-reserve",
] as const;

export type LowerMainlandJurisdictionId =
  (typeof lowerMainlandJurisdictionIds)[number];

export type OfficialSourceReference = {
  name: string;
  url: string;
  updateNote: string;
};

export type JurisdictionDescriptor = {
  id: LowerMainlandJurisdictionId;
  name: string;
  regionalArea:
    | "Metro Vancouver"
    | "Fraser Valley Regional District"
    | "First Nation reserve or treaty land";
  kind: "MUNICIPALITY" | "ELECTORAL_AREA" | "FIRST_NATION";
  status: PropertyProviderStatus;
  boundaryName?: string;
  localityNames?: readonly string[];
  addressResolution: string;
  zoningResolution: string;
  parcelGeometry: string;
  greenSupported: boolean;
  legalTerminology?: string;
  limitations: string;
  propertySource: OfficialSourceReference;
  zoningSource: OfficialSourceReference;
  ruleSource: OfficialSourceReference;
  lastChecked: string;
};

const liveMap = (name: string, url: string): OfficialSourceReference => ({
  name,
  url,
  updateNote: "Live municipal map or data service; checked on the audit date.",
});

const currentPage = (name: string, url: string): OfficialSourceReference => ({
  name,
  url,
  updateNote: "Current official page or consolidated document; checked on the audit date.",
});

const descriptor = (
  input: Omit<JurisdictionDescriptor, "lastChecked">,
): JurisdictionDescriptor => ({ ...input, lastChecked: lowerMainlandAuditDate });

export const lowerMainlandJurisdictions: readonly JurisdictionDescriptor[] = [
  descriptor({
    id: "anmore",
    name: "Village of Anmore",
    regionalArea: "Metro Vancouver",
    kind: "MUNICIPALITY",
    status: "LOOKUP_ONLY",
    boundaryName: "Village of Anmore",
    addressResolution: "BC Address Geocoder plus Metro Vancouver municipal boundary",
    zoningResolution: "Official map and bylaw available for human review",
    parcelGeometry: "Visible in the official map; not used by the automated classifier",
    greenSupported: false,
    legalTerminology: "Accessory dwelling use requires municipal confirmation",
    limitations: "No validated machine rule set for parcel-specific accessory dwelling eligibility.",
    propertySource: liveMap("Village of Anmore Maps", "https://anmore.com/services/maps/"),
    zoningSource: liveMap("Village of Anmore Maps", "https://anmore.com/services/maps/"),
    ruleSource: currentPage("Village of Anmore Zoning Bylaw No. 568, 2017 (consolidated)", "https://anmore.com/wp-content/uploads/2026/01/Bylaw-568-2017-Zoning-Bylaw-Consolidated.pdf"),
  }),
  descriptor({
    id: "belcarra",
    name: "Village of Belcarra",
    regionalArea: "Metro Vancouver",
    kind: "MUNICIPALITY",
    status: "LOOKUP_ONLY",
    boundaryName: "Village of Belcarra",
    addressResolution: "BC Address Geocoder plus Metro Vancouver municipal boundary",
    zoningResolution: "Official GIS available for human review",
    parcelGeometry: "Visible in the official GIS; not used by the automated classifier",
    greenSupported: false,
    limitations: "No validated public parcel-to-rule API or current machine rule set.",
    propertySource: liveMap("Village of Belcarra GIS", "https://belcarra.ca/gis/"),
    zoningSource: liveMap("Village of Belcarra GIS", "https://belcarra.ca/gis/"),
    ruleSource: currentPage("Village of Belcarra Bylaws", "https://belcarra.ca/municipal-hall/bylaws/"),
  }),
  descriptor({
    id: "bowen-island",
    name: "Bowen Island Municipality",
    regionalArea: "Metro Vancouver",
    kind: "MUNICIPALITY",
    status: "LOOKUP_ONLY",
    boundaryName: "Bowen Island Municipality",
    addressResolution: "BC Address Geocoder plus Metro Vancouver municipal boundary",
    zoningResolution: "BowMap and current Land Use Bylaw available for human review",
    parcelGeometry: "Visible in BowMap; not used by the automated classifier",
    greenSupported: false,
    limitations: "Island-specific land-use controls require parcel-level human interpretation.",
    propertySource: liveMap("Bowen Island BowMap", "https://bowenislandmunicipality.ca/bowmap/"),
    zoningSource: liveMap("Bowen Island BowMap", "https://bowenislandmunicipality.ca/bowmap/"),
    ruleSource: currentPage("Bowen Island Land Use Bylaw and schedules", "https://bowenislandmunicipality.ca/land-use-bylaw-amendments-schedules/"),
  }),
  descriptor({
    id: "burnaby",
    name: "City of Burnaby",
    regionalArea: "Metro Vancouver",
    kind: "MUNICIPALITY",
    status: "PARTIAL",
    boundaryName: "City of Burnaby",
    addressResolution: "BC Address Geocoder plus Metro Vancouver municipal boundary",
    zoningResolution: "Official ArcGIS zoning polygons are machine-readable",
    parcelGeometry: "Official open-data geometry is available; eligibility geometry is not automated",
    greenSupported: false,
    legalTerminology: "Laneway home / small-scale multi-unit housing",
    limitations: "Zoning can be queried, but the complete current parcel conditions and accessory dwelling rules are not automated.",
    propertySource: liveMap("City of Burnaby Maps and Open Data", "https://www.burnaby.ca/services-and-payments/maps-and-open-data"),
    zoningSource: liveMap("City of Burnaby OpenData Zoning ArcGIS layer", "https://gis.burnaby.ca/arcgis/rest/services/OpenData/OpenData1/MapServer/8"),
    ruleSource: currentPage("City of Burnaby Zoning Bylaw", "https://www.burnaby.ca/our-city/bylaws/zoning-bylaw"),
  }),
  descriptor({
    id: "coquitlam",
    name: "City of Coquitlam",
    regionalArea: "Metro Vancouver",
    kind: "MUNICIPALITY",
    status: "LOOKUP_ONLY",
    boundaryName: "City of Coquitlam",
    addressResolution: "BC Address Geocoder plus Metro Vancouver municipal boundary",
    zoningResolution: "QtheMap and current zoning bylaw available for human review",
    parcelGeometry: "Visible in QtheMap; municipal terms preclude treating it as an authoritative automated decision",
    greenSupported: false,
    legalTerminology: "Small-scale multi-unit housing",
    limitations: "The City directs users to verify property dimensions and controls; no validated automated rule set.",
    propertySource: liveMap("City of Coquitlam QtheMap and spatial catalogue", "https://www.coquitlam.ca/701/City-Maps"),
    zoningSource: currentPage("City of Coquitlam Zoning Bylaw", "https://www.coquitlam.ca/562/Zoning-Bylaw"),
    ruleSource: currentPage("City of Coquitlam Small-Scale Multi-Unit Housing", "https://www.coquitlam.ca/1038/Information-for-Building-Small-Scale-Mul"),
  }),
  descriptor({
    id: "delta",
    name: "City of Delta",
    regionalArea: "Metro Vancouver",
    kind: "MUNICIPALITY",
    status: "PARTIAL",
    boundaryName: "City of Delta",
    addressResolution: "BC Address Geocoder plus Metro Vancouver municipal boundary",
    zoningResolution: "DeltaMap ArcGIS zoning polygons are machine-readable",
    parcelGeometry: "Official parcel, ALR, zoning and SSMUH layers are available",
    greenSupported: false,
    legalTerminology: "Secondary residential unit / small-scale multi-unit housing",
    limitations: "Parcel constraints and the full current rule conditions are not yet automated.",
    propertySource: liveMap("City of Delta Property Basemap ArcGIS service", "https://mw1.delta.ca/arcgis/rest/services/DeltaMap/PropertyBasemap/MapServer"),
    zoningSource: liveMap("City of Delta Zoning ArcGIS layer", "https://maps.delta.ca/arcgis/rest/services/DeltaMap/Planning/MapServer/11"),
    ruleSource: currentPage("City of Delta DeltaMap", "https://www.delta.ca/about-delta/deltamap"),
  }),
  descriptor({
    id: "langley-city",
    name: "City of Langley",
    regionalArea: "Metro Vancouver",
    kind: "MUNICIPALITY",
    status: "PARTIAL",
    boundaryName: "City of Langley",
    addressResolution: "BC Address Geocoder plus Metro Vancouver municipal boundary",
    zoningResolution: "Official ArcGIS zoning polygons are machine-readable",
    parcelGeometry: "Official basemap parcel geometry is available",
    greenSupported: false,
    limitations: "Zoning Bylaw 3300 is current, but parcel-specific accessory dwelling conditions are not automated.",
    propertySource: liveMap("City of Langley Basemap parcel layer", "https://maps.langleycity.ca/server/rest/services/Maps/Basemap/MapServer/192"),
    zoningSource: liveMap("City of Langley Zoning ArcGIS layer", "https://maps.langleycity.ca/server/rest/services/Maps/External/MapServer/90"),
    ruleSource: currentPage("City of Langley Zoning Bylaw 2025 No. 3300", "https://www.langleycity.ca/business-development/planning-zoning/zoning-bylaw"),
  }),
  descriptor({
    id: "langley-township",
    name: "Township of Langley",
    regionalArea: "Metro Vancouver",
    kind: "MUNICIPALITY",
    status: "LOOKUP_ONLY",
    boundaryName: "Township of Langley",
    addressResolution: "BC Address Geocoder plus Metro Vancouver municipal boundary",
    zoningResolution: "GeoSource and municipal development-potential tools support human lookup",
    parcelGeometry: "Official map/open data is available but not validated for automated screening",
    greenSupported: false,
    limitations: "Lot dimensions, watercourses, ALR, access and development permit conditions require verification.",
    propertySource: liveMap("Township of Langley GeoSource and maps", "https://www.tol.ca/en/connect/maps.aspx"),
    zoningSource: liveMap("Township of Langley property development potential", "https://www.tol.ca/en/building-development/determine-your-property-development-potential.aspx"),
    ruleSource: currentPage("Township of Langley Zoning Bylaw", "https://www.tol.ca/en/building-development/zoning-bylaw.aspx"),
  }),
  descriptor({
    id: "lions-bay",
    name: "Village of Lions Bay",
    regionalArea: "Metro Vancouver",
    kind: "MUNICIPALITY",
    status: "LOOKUP_ONLY",
    boundaryName: "Village of Lions Bay",
    addressResolution: "BC Address Geocoder plus Metro Vancouver municipal boundary",
    zoningResolution: "Official zoning map and consolidated bylaw available for human review",
    parcelGeometry: "Municipal GIS is under redevelopment; no runtime dependency",
    greenSupported: false,
    limitations: "Municipal GIS availability and steep-site conditions prevent safe automated eligibility.",
    propertySource: liveMap("Village of Lions Bay GIS", "https://www.lionsbay.ca/municipal-services/gis-geographic-information-system"),
    zoningSource: currentPage("Village of Lions Bay Zoning Map", "https://www.lionsbay.ca/sites/2/files/docs/bylaws/zoning_map.pdf"),
    ruleSource: currentPage("Village of Lions Bay Zoning and Development Bylaw No. 520", "https://www.lionsbay.ca/government/bylaws/bylaw/zoning-and-development-bylaw-no-520-2017-consolidation"),
  }),
  descriptor({
    id: "maple-ridge",
    name: "City of Maple Ridge",
    regionalArea: "Metro Vancouver",
    kind: "MUNICIPALITY",
    status: "PARTIAL",
    boundaryName: "City of Maple Ridge",
    addressResolution: "BC Address Geocoder plus Metro Vancouver municipal boundary",
    zoningResolution: "Official RidgeView ArcGIS zoning polygons are machine-readable",
    parcelGeometry: "Official GIS geometry is available; eligibility geometry is not automated",
    greenSupported: false,
    limitations: "Current zoning can be identified technically, but complete detached accessory dwelling conditions are not automated.",
    propertySource: liveMap("City of Maple Ridge RidgeView", "https://www.mapleridge.ca/build-do-business/community-planning/maps-open-data"),
    zoningSource: liveMap("City of Maple Ridge RidgeView zoning layer", "https://geoservices.mapleridge.ca/server/rest/services/RidgeViewData/Development/MapServer/18"),
    ruleSource: currentPage("City of Maple Ridge Zoning Bylaw", "https://www.mapleridge.ca/build-do-business/community-planning/zoning-bylaw"),
  }),
  descriptor({
    id: "new-westminster",
    name: "City of New Westminster",
    regionalArea: "Metro Vancouver",
    kind: "MUNICIPALITY",
    status: "LOOKUP_ONLY",
    boundaryName: "City of New Westminster",
    addressResolution: "BC Address Geocoder plus Metro Vancouver municipal boundary",
    zoningResolution: "CityViews and the Property Portal support official human lookup",
    parcelGeometry: "Visible in official tools; no validated public runtime parcel API",
    greenSupported: false,
    limitations: "Zoning and legal parcel facts require lookup in CityViews/Property Portal and rule interpretation.",
    propertySource: liveMap("New Westminster Property Inquiry and CityViews", "https://www.newwestcity.ca/property-inquiry-information"),
    zoningSource: liveMap("New Westminster Property Inquiry and CityViews", "https://www.newwestcity.ca/property-inquiry-information"),
    ruleSource: currentPage("New Westminster Zoning Bylaw", "https://www.newwestcity.ca/development-policies-and-process/making-a-development-application/sb_expander_articles/542.php"),
  }),
  descriptor({
    id: "north-vancouver-city",
    name: "City of North Vancouver",
    regionalArea: "Metro Vancouver",
    kind: "MUNICIPALITY",
    status: "PARTIAL",
    boundaryName: "City of North Vancouver",
    addressResolution: "BC Address Geocoder plus Metro Vancouver municipal boundary",
    zoningResolution: "CityMAP ArcGIS zoning polygons are machine-readable",
    parcelGeometry: "Official CityMAP layers are available",
    greenSupported: false,
    limitations: "City and District are distinguished, but parcel-specific accessory dwelling eligibility is not automated.",
    propertySource: liveMap("City of North Vancouver CityMap", "https://gisext2.cnv.org/apps/CityMAP/index.html"),
    zoningSource: liveMap("City of North Vancouver CityMap zoning layer", "https://gisext2.cnv.org/arcgis/rest/services/BaseMapServices/CityMapPro/MapServer/40"),
    ruleSource: currentPage("City of North Vancouver Zoning Bylaw", "https://www.cnv.org/City-Hall/Bylaws/Zoning-Bylaw"),
  }),
  descriptor({
    id: "north-vancouver-district",
    name: "District of North Vancouver",
    regionalArea: "Metro Vancouver",
    kind: "MUNICIPALITY",
    status: "LOOKUP_ONLY",
    boundaryName: "District of North Vancouver",
    addressResolution: "BC Address Geocoder plus Metro Vancouver municipal boundary",
    zoningResolution: "GEOweb publishes official zoning and property data with weekly refreshes",
    parcelGeometry: "Downloadable official parcel geometry is available",
    greenSupported: false,
    limitations: "Current zoning and parcels are available, but terrain, hazards and accessory dwelling conditions are not automated.",
    propertySource: liveMap("District of North Vancouver GEOweb Open Data", "https://geoweb.dnv.org/data/"),
    zoningSource: liveMap("District of North Vancouver GEOweb", "https://geoweb.dnv.org/"),
    ruleSource: currentPage("District of North Vancouver Zoning Bylaw", "https://www.dnv.org/government-administration/bylaws/zoning-bylaw"),
  }),
  descriptor({
    id: "pitt-meadows",
    name: "City of Pitt Meadows",
    regionalArea: "Metro Vancouver",
    kind: "MUNICIPALITY",
    status: "LOOKUP_ONLY",
    boundaryName: "City of Pitt Meadows",
    addressResolution: "BC Address Geocoder plus Metro Vancouver municipal boundary",
    zoningResolution: "Mapview property reports and zoning pages support human lookup",
    parcelGeometry: "Visible in official maps; no validated runtime parcel API",
    greenSupported: false,
    limitations: "ALR, utilities, easements and flood conditions require parcel-level human review.",
    propertySource: liveMap("Pitt Meadows Property Reports and Records", "https://www.pittmeadows.ca/business-and-building/property-development/property-reports-and-records"),
    zoningSource: currentPage("Pitt Meadows Zoning and Land Use", "https://www.pittmeadows.ca/business-and-building/zoning-and-land-use"),
    ruleSource: currentPage("Pitt Meadows Zoning Bylaw No. 2505", "https://www.pittmeadows.ca/city-hall/bylaws-policies/bylaws/zoning-bylaw-no-2505-2011-consolidated-version"),
  }),
  descriptor({
    id: "port-coquitlam",
    name: "City of Port Coquitlam",
    regionalArea: "Metro Vancouver",
    kind: "MUNICIPALITY",
    status: "LOOKUP_ONLY",
    boundaryName: "City of Port Coquitlam",
    addressResolution: "BC Address Geocoder plus Metro Vancouver municipal boundary",
    zoningResolution: "PoCoMap supports human lookup; its terms do not support this automated service",
    parcelGeometry: "Visible in PoCoMap; not consumed by this classifier",
    greenSupported: false,
    limitations: "PoCoMap terms restrict service-bureau use; only jurisdiction routing is automated.",
    propertySource: liveMap("City of Port Coquitlam PoCoMap", "https://www.portcoquitlam.ca/business-development/pocomap"),
    zoningSource: liveMap("City of Port Coquitlam PoCoMap", "https://www.portcoquitlam.ca/business-development/pocomap"),
    ruleSource: currentPage("City of Port Coquitlam Rezoning and Zoning Information", "https://www.portcoquitlam.ca/business-development/property-development-building/land-use-subdivision/rezoning-application"),
  }),
  descriptor({
    id: "port-moody",
    name: "City of Port Moody",
    regionalArea: "Metro Vancouver",
    kind: "MUNICIPALITY",
    status: "LOOKUP_ONLY",
    boundaryName: "City of Port Moody",
    addressResolution: "BC Address Geocoder plus Metro Vancouver municipal boundary",
    zoningResolution: "ViewPort supports official zoning, property and constraint lookup",
    parcelGeometry: "Available through ViewPort/open data; not validated for automated classification",
    greenSupported: false,
    limitations: "Watercourses and other parcel constraints require human review.",
    propertySource: liveMap("City of Port Moody ViewPort", "https://www.portmoody.ca/news-and-notices/posts/port-moody-launches-updated-mapping-system/"),
    zoningSource: liveMap("City of Port Moody ViewPort", "https://www.portmoody.ca/news-and-notices/posts/port-moody-launches-updated-mapping-system/"),
    ruleSource: currentPage("Port Moody Small-Scale Multi-Unit Housing", "https://www.portmoody.ca/common/Services/eDocs.ashx?docnumber=638906"),
  }),
  descriptor({
    id: "richmond",
    name: "City of Richmond",
    regionalArea: "Metro Vancouver",
    kind: "MUNICIPALITY",
    status: "LOOKUP_ONLY",
    boundaryName: "City of Richmond",
    addressResolution: "BC Address Geocoder plus Metro Vancouver municipal boundary",
    zoningResolution: "Richmond Interactive Map links parcels to zoning and bylaws",
    parcelGeometry: "Visible in the official map; no validated public runtime parcel API",
    greenSupported: false,
    limitations: "Flood construction levels and parcel-specific development conditions require human review.",
    propertySource: liveMap("City of Richmond Interactive Map", "https://www.richmond.ca/services/digital/maps.htm"),
    zoningSource: liveMap("City of Richmond Interactive Map", "https://www.richmond.ca/services/digital/maps.htm"),
    ruleSource: currentPage("City of Richmond Zoning Bylaw", "https://www.richmond.ca/business-development/building-approvals/zoning/zoningbylaw.htm"),
  }),
  descriptor({
    id: "surrey",
    name: "City of Surrey",
    regionalArea: "Metro Vancouver",
    kind: "MUNICIPALITY",
    status: "LOOKUP_ONLY",
    boundaryName: "City of Surrey",
    addressResolution: "BC Address Geocoder plus Metro Vancouver municipal boundary",
    zoningResolution: "COSMOS exposes official zoning and property layers for human lookup",
    parcelGeometry: "Visible in COSMOS; no validated supported runtime query integrated",
    greenSupported: false,
    limitations: "Zoning, ALR, watercourse and lot conditions require municipal property review.",
    propertySource: liveMap("City of Surrey COSMOS", "https://www.surrey.ca/services-payments/online-services/maps-cosmos"),
    zoningSource: liveMap("City of Surrey COSMOS Metadata", "https://cosmos.surrey.ca/external/tools/Metadata/metadata_external.html"),
    ruleSource: currentPage("City of Surrey Zoning Bylaw", "https://www.surrey.ca/city-government/bylaws/zoning-bylaw"),
  }),
  descriptor({
    id: "vancouver",
    name: "City of Vancouver",
    regionalArea: "Metro Vancouver",
    kind: "MUNICIPALITY",
    status: "FULL",
    boundaryName: "City of Vancouver",
    addressResolution: "BC Address Geocoder, Metro Vancouver boundary, and exact City parcel match",
    zoningResolution: "Official City parcel, zoning polygon and tax datasets are queried and cross-checked",
    parcelGeometry: "Official City parcel geometry and centroid are returned",
    greenSupported: true,
    legalTerminology: "Laneway house under R1-1 lower-density housing rules",
    limitations: "Green remains preliminary; site-specific, title, servicing, survey and permitting checks remain required.",
    propertySource: liveMap("City of Vancouver Property Parcel Polygons", "https://opendata.vancouver.ca/explore/dataset/property-parcel-polygons/"),
    zoningSource: liveMap("City of Vancouver Zoning Districts and Labels", "https://opendata.vancouver.ca/explore/dataset/zoning-districts-and-labels/"),
    ruleSource: currentPage("City of Vancouver R1-1 District Schedule", "https://bylaws.vancouver.ca/zoning/zoning-by-law-district-schedule-r1-1.pdf"),
  }),
  descriptor({
    id: "west-vancouver",
    name: "District of West Vancouver",
    regionalArea: "Metro Vancouver",
    kind: "MUNICIPALITY",
    status: "LOOKUP_ONLY",
    boundaryName: "District of West Vancouver",
    addressResolution: "BC Address Geocoder plus Metro Vancouver municipal boundary",
    zoningResolution: "WESTMap/zoning map supports official human lookup",
    parcelGeometry: "Visible in official maps; no validated runtime parcel API",
    greenSupported: false,
    limitations: "Slope, creek, wildfire and development permit constraints require site-specific review.",
    propertySource: liveMap("District of West Vancouver Maps and Open Data", "https://westvancouver.ca/business-development/building-development/maps"),
    zoningSource: liveMap("District of West Vancouver Zoning Map", "https://westvancouver.ca/business-development/building-development/zoning-map"),
    ruleSource: currentPage("District of West Vancouver Development Regulations", "https://westvancouver.ca/business-development/building-development/development-regulations"),
  }),
  descriptor({
    id: "white-rock",
    name: "City of White Rock",
    regionalArea: "Metro Vancouver",
    kind: "MUNICIPALITY",
    status: "PARTIAL",
    boundaryName: "City of White Rock",
    addressResolution: "BC Address Geocoder plus Metro Vancouver municipal boundary",
    zoningResolution: "Official WROMS ArcGIS zoning polygons are machine-readable",
    parcelGeometry: "Official WROMS parcel geometry is available",
    greenSupported: false,
    legalTerminology: "Small-scale multi-unit housing",
    limitations: "The City cautions against commitment decisions from GIS; full parcel and SSMUH conditions are not automated.",
    propertySource: liveMap("City of White Rock WROMS", "https://www.whiterockcity.ca/335/WROMS---White-Rock-Online-Mapping-System"),
    zoningSource: liveMap("City of White Rock Open Data Zoning ArcGIS service", "https://maps.whiterockcity.ca/server/rest/services/opendata/Zoning/MapServer"),
    ruleSource: currentPage("City of White Rock Zoning Bylaw 2024 No. 2506", "https://www.whiterockcity.ca/DocumentCenter/View/8003/Zoning-Bylaw-2024-No-2506-Adopted-June-27-2024"),
  }),
  descriptor({
    id: "metro-electoral-area-a",
    name: "Metro Vancouver Electoral Area A / UBC-UEL area",
    regionalArea: "Metro Vancouver",
    kind: "ELECTORAL_AREA",
    status: "SPECIAL_JURISDICTION",
    addressResolution: "BC Address Geocoder plus exclusion from Metro municipal boundaries",
    zoningResolution: "Separate UBC, UEL, Islands Trust, regional and reserve governance requires human review",
    parcelGeometry: "Not used for automated classification",
    greenSupported: false,
    limitations: "Governance varies within Electoral Area A; neighbouring Vancouver rules are never applied.",
    propertySource: currentPage("Metro Vancouver Electoral Area A", "https://metrovancouver.org/services/electoral-area-a"),
    zoningSource: currentPage("Metro Vancouver Electoral Area A Official Community Plan", "https://metrovancouver.org/services/electoral-area-a/official-community-plan"),
    ruleSource: currentPage("Metro Vancouver Electoral Area A Official Community Plan", "https://metrovancouver.org/services/electoral-area-a/official-community-plan"),
  }),
  descriptor({
    id: "tsawwassen-first-nation",
    name: "Tsawwassen First Nation",
    regionalArea: "Metro Vancouver",
    kind: "FIRST_NATION",
    status: "SPECIAL_JURISDICTION",
    boundaryName: "Tsawwassen First Nation",
    addressResolution: "BC Address Geocoder plus Metro Vancouver administrative boundary",
    zoningResolution: "Tsawwassen First Nation land governance requires dedicated human review",
    parcelGeometry: "Not used for automated classification",
    greenSupported: false,
    limitations: "Delta zoning is never inherited; treaty land governance requires a dedicated provider.",
    propertySource: currentPage("Tsawwassen First Nation Lands", "https://tsawwassenfirstnation.com/government/lands/"),
    zoningSource: currentPage("Tsawwassen First Nation Lands", "https://tsawwassenfirstnation.com/government/lands/"),
    ruleSource: currentPage("Province of BC Tsawwassen Final Agreement implementation report", "https://www2.gov.bc.ca/assets/gov/environment/natural-resource-stewardship/consulting-with-first-nations/agreements/tsawwassen_implementationreport_en_15_17_final_web.pdf"),
  }),
  descriptor({
    id: "abbotsford",
    name: "City of Abbotsford",
    regionalArea: "Fraser Valley Regional District",
    kind: "MUNICIPALITY",
    status: "LOOKUP_ONLY",
    localityNames: ["ABBOTSFORD"],
    addressResolution: "BC Address Geocoder authoritative locality",
    zoningResolution: "Official WebMap and municipal ArcGIS services support property/zoning lookup",
    parcelGeometry: "Official GIS geometry is available; eligibility geometry is not automated",
    greenSupported: false,
    limitations: "ALR, servicing, floodplain and accessory dwelling conditions are not automated.",
    propertySource: liveMap("City of Abbotsford WebMap", "https://www.abbotsford.ca/city-services/mapping-data-analytics/webmap"),
    zoningSource: liveMap("City of Abbotsford WebMap", "https://www.abbotsford.ca/city-services/mapping-data-analytics/webmap"),
    ruleSource: currentPage("City of Abbotsford Development Planning", "https://www.abbotsford.ca/business-development/development-planning"),
  }),
  descriptor({
    id: "chilliwack",
    name: "City of Chilliwack",
    regionalArea: "Fraser Valley Regional District",
    kind: "MUNICIPALITY",
    status: "LOOKUP_ONLY",
    localityNames: ["CHILLIWACK"],
    addressResolution: "BC Address Geocoder authoritative locality",
    zoningResolution: "Official WebMap exposes zoning and SSMUH-related layers",
    parcelGeometry: "Official map data is available; automated parcel rules are not implemented",
    greenSupported: false,
    limitations: "Urban growth boundary, servicing, flood and parcel-specific conditions require human review.",
    propertySource: liveMap("City of Chilliwack Mapping and Open Data", "https://www.chilliwack.com/main/page.cfm?id=2274"),
    zoningSource: liveMap("City of Chilliwack Mapping and Open Data", "https://www.chilliwack.com/main/page.cfm?id=2274"),
    ruleSource: currentPage("City of Chilliwack Small-Scale Multi-Unit Housing WebMap guidance", "https://www.chilliwack.com/main/attachments/attachView.cfm?attachID=8464"),
  }),
  descriptor({
    id: "harrison-hot-springs",
    name: "Village of Harrison Hot Springs",
    regionalArea: "Fraser Valley Regional District",
    kind: "MUNICIPALITY",
    status: "LOOKUP_ONLY",
    localityNames: ["HARRISON HOT SPRINGS"],
    addressResolution: "BC Address Geocoder authoritative locality",
    zoningResolution: "FVRD Regional Information Map and current Village bylaw support human lookup",
    parcelGeometry: "Visible in the FVRD map; not used for automated classification",
    greenSupported: false,
    limitations: "Flood and site-specific Village controls require human review.",
    propertySource: liveMap("FVRD Regional Information Map", "https://www.fvrd.ca/EN/main/services/mapping/regional-information-map.html"),
    zoningSource: currentPage("Harrison Hot Springs Development", "https://www.harrisonhotsprings.ca/development"),
    ruleSource: currentPage("Harrison Hot Springs Zoning Bylaw No. 1115 (consolidated)", "https://www.harrisonhotsprings.ca/sites/default/files/2026-03/Zoning-Bylaw-No.-1115--%28Consolidated-to-December-15%2C-2025%29.pdf"),
  }),
  descriptor({
    id: "hope",
    name: "District of Hope",
    regionalArea: "Fraser Valley Regional District",
    kind: "MUNICIPALITY",
    status: "LOOKUP_ONLY",
    localityNames: ["HOPE"],
    addressResolution: "BC Address Geocoder authoritative locality",
    zoningResolution: "Official online mapping and current planning pages support human lookup",
    parcelGeometry: "Visible in official mapping; not used for automated classification",
    greenSupported: false,
    limitations: "The zoning bylaw is under transition following the 2026 OCP; no Green result is safe.",
    propertySource: liveMap("District of Hope Online Mapping", "https://hope.ca/online-mapping"),
    zoningSource: currentPage("District of Hope Official Community Plan and Zoning Bylaw", "https://hope.ca/official-community-plan-and-zoning-bylaw"),
    ruleSource: currentPage("District of Hope Official Community Plan and Zoning Bylaw", "https://hope.ca/official-community-plan-and-zoning-bylaw"),
  }),
  descriptor({
    id: "kent",
    name: "District of Kent",
    regionalArea: "Fraser Valley Regional District",
    kind: "MUNICIPALITY",
    status: "LOOKUP_ONLY",
    localityNames: ["KENT", "AGASSIZ"],
    addressResolution: "BC Address Geocoder authoritative locality, including Agassiz",
    zoningResolution: "Official GIS and zoning pages support human lookup",
    parcelGeometry: "Visible in official mapping; not used for automated classification",
    greenSupported: false,
    legalTerminology: "Detached accessory dwelling unit",
    limitations: "ALR, flood, servicing and development permit conditions are not automated.",
    propertySource: liveMap("District of Kent Mapping and GIS", "https://www.kentbc.ca/living-here/mapping-and-gis/"),
    zoningSource: currentPage("District of Kent OCP and Zoning", "https://www.kentbc.ca/business-and-development/development-and-planning/ocp-and-zoning/"),
    ruleSource: currentPage("District of Kent OCP and Zoning", "https://www.kentbc.ca/business-and-development/development-and-planning/ocp-and-zoning/"),
  }),
  descriptor({
    id: "mission",
    name: "City of Mission",
    regionalArea: "Fraser Valley Regional District",
    kind: "MUNICIPALITY",
    status: "PARTIAL",
    localityNames: ["MISSION"],
    addressResolution: "BC Address Geocoder authoritative locality",
    zoningResolution: "Official WebMap/ArcGIS planning service exposes zoning",
    parcelGeometry: "Official GIS geometry is available; eligibility geometry is not automated",
    greenSupported: false,
    limitations: "Slope, hazard, servicing and accessory dwelling conditions require human review.",
    propertySource: liveMap("City of Mission WebMap", "https://www.mission.ca/webmap"),
    zoningSource: liveMap("City of Mission Planning ArcGIS service", "https://esri.mission.ca/ags/rest/services/Geocortex/Planning/MapServer"),
    ruleSource: currentPage("City of Mission Zoning Bylaw", "https://www.mission.ca/city-hall/bylaws/zoning-bylaw"),
  }),
  descriptor({
    id: "fvrd-electoral-area",
    name: "Fraser Valley Regional District electoral area",
    regionalArea: "Fraser Valley Regional District",
    kind: "ELECTORAL_AREA",
    status: "SPECIAL_JURISDICTION",
    addressResolution: "BC Address Geocoder electoral-area metadata",
    zoningResolution: "FVRD mapping and zoning require electoral-area-specific human review",
    parcelGeometry: "Visible in the FVRD map; not used for automated classification",
    greenSupported: false,
    limitations: "Rules vary by electoral area; neighbouring municipal rules are never applied.",
    propertySource: liveMap("FVRD Regional Information Map", "https://www.fvrd.ca/EN/main/services/mapping/regional-information-map.html"),
    zoningSource: currentPage("FVRD Zoning Bylaw Update and Consolidation", "https://haveyoursay.fvrd.ca/zoning"),
    ruleSource: currentPage("FVRD Zoning Bylaw Update and Consolidation", "https://haveyoursay.fvrd.ca/zoning"),
  }),
  descriptor({
    id: "first-nation-reserve",
    name: "First Nation reserve or treaty land",
    regionalArea: "First Nation reserve or treaty land",
    kind: "FIRST_NATION",
    status: "SPECIAL_JURISDICTION",
    addressResolution: "BC Address Geocoder locality metadata where identifiable",
    zoningResolution: "The identified First Nation or federal/treaty authority requires dedicated review",
    parcelGeometry: "Not used for automated classification",
    greenSupported: false,
    limitations: "No neighbouring municipal zoning or regional rules are inherited.",
    propertySource: currentPage("BC Address Geocoder", "https://digital.gov.bc.ca/bcgov-common-components/bc-address-geocoder/"),
    zoningSource: currentPage("Indigenous Services Canada First Nation Profiles", "https://fnp-ppn.aadnc-aandc.gc.ca/fnp/Main/index.aspx?lang=eng"),
    ruleSource: currentPage("Government of Canada First Nations Land Management", "https://www.sac-isc.gc.ca/eng/1327090675492/1611953585165"),
  }),
] as const;

const jurisdictionById = new Map(
  lowerMainlandJurisdictions.map((jurisdiction) => [
    jurisdiction.id,
    jurisdiction,
  ]),
);

const jurisdictionByBoundaryName = new Map(
  lowerMainlandJurisdictions.flatMap((jurisdiction) =>
    jurisdiction.boundaryName
      ? [[jurisdiction.boundaryName.toUpperCase(), jurisdiction] as const]
      : [],
  ),
);

const jurisdictionByLocalityName = new Map(
  lowerMainlandJurisdictions.flatMap((jurisdiction) =>
    (jurisdiction.localityNames ?? []).map(
      (locality) => [locality.toUpperCase(), jurisdiction] as const,
    ),
  ),
);

export function getJurisdictionDescriptor(
  id: LowerMainlandJurisdictionId,
) {
  const descriptor = jurisdictionById.get(id);
  if (!descriptor) throw new Error(`Unknown jurisdiction: ${id}`);
  return descriptor;
}

export function getJurisdictionByBoundaryName(name: string) {
  return jurisdictionByBoundaryName.get(name.trim().toUpperCase());
}

export function getFraserJurisdictionByLocality(name: string) {
  return jurisdictionByLocalityName.get(name.trim().toUpperCase());
}
